/* Local financial overview. Private current App state only; never reads shared snapshots. */
(function(root){'use strict';
const App=root.App,V6=root.V6,V7=root.V7,C=root.Core,I=root.MasarifiIntelligence;if(!App||!V6||!V7||!C||!I)return;
V6.addLabels(`
v87CashBalance|رصيد الصناديق في نهاية الفترة|Dönem sonu kasa bakiyesi|Cashbox balance at period end|Solde des caisses en fin de période
v87NetHint|الصافي هو الإيرادات ناقص المصروفات خلال الفترة. الرصيد يشمل الافتتاح والتحويلات حتى تاريخ النهاية.|Net, dönem gelirleri eksi giderlerdir. Bakiye, bitiş tarihine kadar açılışı ve transferleri de içerir.|Net is income minus expenses in this period. Balance also includes opening funds and transfers through the end date.|Le net est le revenu moins les dépenses de la période. Le solde inclut aussi les fonds initiaux et les transferts jusqu’à la date de fin.
v87SelectedPeriod|الفترة المختارة|Seçilen dönem|Selected period|Période sélectionnée
v87PriorPeriod|المقارنة مع الفترة السابقة بنفس عدد الأيام.|Önceki aynı uzunluktaki dönemle karşılaştırma.|Compared with the immediately preceding period of the same length.|Comparaison avec la période précédente de même durée.

intelligenceTitle|نظرة مالية|Finansal görünüm|Financial overview|Vue financière
intelligenceHint|أرقام واضحة من سجلك الحالي، دون خلط العملات.|Güncel kayıtlarınızdan net rakamlar; para birimleri ayrı tutulur.|Clear figures from your current ledger, with currencies kept separate.|Des chiffres clairs issus de vos mouvements, sans mélanger les devises.
intelligenceLocal|تحليل محلي محسوب، وليس ردًا من نموذج ذكاء اصطناعي.|Yerel hesaplanan analiz; bir yapay zekâ modelinin yanıtı değildir.|Calculated locally; this overview is not a response from an AI model.|Calculé localement ; cette vue n’est pas une réponse d’un modèle d’IA.
intelligencePrivate|هذه النظرة متاحة في مساحتك الشخصية بعد فتح القفل.|Bu görünüm, kilidi açılmış kişisel alanınızda kullanılabilir.|This overview is available in your unlocked personal workspace.|Cette vue est disponible dans votre espace personnel déverrouillé.
intelligenceScope|إيرادات ومصروفات القسم المحدد، بما فيها رسوم التحويل. التحويلات والأرصدة الافتتاحية ليست دخلًا أو مصروفًا.|Seçili bölümün gelir, gider ve transfer ücretleri. Transfer ve açılış bakiyeleri gelir veya gider değildir.|Selected-section income and expenses, including transfer fees. Transfers and opening balances are not income or expenses.|Revenus et dépenses de la section, frais de transfert inclus. Transferts et soldes initiaux ne sont pas des revenus ou dépenses.
intelligencePeriod|هذا الشهر حتى اليوم|Bu ay, bugüne kadar|This month to date|Ce mois jusqu’à aujourd’hui
intelligencePrior|الفترة المقابلة من الشهر السابق|Önceki ayın eşdeğer dönemi|Equivalent previous-month period|Période équivalente du mois précédent
intelligenceComparison|مقارنة عادلة لعدد الأيام المنقضي؛ يُضبط آخر الشهر عند الحاجة.|Geçen gün sayısına göre karşılaştırma; ay sonu gerektiğinde ayarlanır.|Comparison uses elapsed calendar days, clipped at the previous month-end.|Comparaison du nombre de jours écoulés, limitée à la fin du mois précédent.
intelligenceExpenseChange|تغير المصروفات|Gider değişimi|Expense change|Variation des dépenses
intelligenceNoPrior|لا توجد مصروفات في الفترة السابقة للمقارنة.|Önceki dönemde karşılaştırılacak gider yok.|No previous-period expenses to compare.|Aucune dépense antérieure à comparer.
intelligenceCategories|مقارنة الفئات|Kategori karşılaştırması|Category comparison|Comparaison des catégories
intelligenceCategoryHint|أكبر 8 فئات حسب مبلغ الفترة الحالية.|Güncel dönem tutarına göre ilk 8 kategori.|Top 8 categories by current-period amount.|Les 8 premières catégories par montant actuel.
intelligenceBudget|وتيرة الميزانية|Bütçe temposu|Budget pacing|Rythme du budget
intelligenceBudgetLimit|ميزانية الشهر|Aylık bütçe|Monthly budget|Budget mensuel
intelligenceExpected|المتوقع حتى اليوم بتوزيع يومي متساوٍ|Eşit günlük dağılımla bugüne kadar beklenen|Expected to date at an even daily pace|Montant attendu à ce jour au rythme quotidien constant
intelligencePaceOver|الإنفاق أعلى من الوتيرة اليومية للميزانية.|Harcama günlük bütçe temposunun üzerinde.|Spending is above the budget’s daily pace.|Les dépenses dépassent le rythme quotidien du budget.
intelligencePaceWithin|الإنفاق ضمن الوتيرة اليومية للميزانية.|Harcama günlük bütçe temposu içinde.|Spending is within the budget’s daily pace.|Les dépenses respectent le rythme quotidien du budget.
intelligenceForecast|تقدير المصروفات لنهاية الشهر|Ay sonu gider tahmini|Month-end expense estimate|Estimation des dépenses en fin de mois
intelligenceForecastHint|حساب تقريبي إذا استمرت وتيرة المصروفات المسجلة؛ ليس توقعًا مضمونًا. لا تُضاف المستحقات مرة أخرى، ولا يشمل حركات غير مسجلة.|Kaydedilen gider temposu sürerse yaklaşık hesap; garanti değildir. Vadeler tekrar eklenmez, kaydedilmemiş işlemler dahil değildir.|An arithmetic estimate if recorded spending continues at this pace; not a guarantee. Dues are not added again, and unrecorded activity is excluded.|Estimation arithmétique si le rythme enregistré se poursuit, sans garantie. Les échéances ne sont pas ajoutées à nouveau et les opérations non enregistrées sont exclues.
intelligenceInsufficient|يلزم مرور 7 أيام من الشهر ووجود مصروفات في 3 أيام مختلفة لتقدير الوتيرة.|Tempo tahmini için ayın en az 7 günü ve 3 farklı günde gider gerekir.|At least 7 elapsed month days and expenses on 3 distinct days are needed to estimate a pace.|Il faut au moins 7 jours écoulés et des dépenses sur 3 jours distincts pour estimer un rythme.
intelligenceEstimateOverflow|المبلغ المتوقع يتجاوز مجال الحساب الدقيق؛ لم يُعرض تقدير.|Tahmini tutar tam hesaplama aralığını aşıyor; tahmin gösterilmedi.|The projected amount exceeds the exact calculation range; no estimate is shown.|Le montant estimé dépasse la plage de calcul exacte ; aucune estimation affichée.
intelligenceDues|المستحقات المتبقية|Kalan vadeler|Remaining dues|Échéances restantes
intelligenceNext7|خلال 7 أيام|Önümüzdeki 7 gün|Next 7 days|7 prochains jours
intelligenceNext30|خلال 30 يومًا|Önümüzdeki 30 gün|Next 30 days|30 prochains jours
intelligenceDueHint|الفترات القادمة تشمل اليوم وتستثني المتأخر؛ المتأخر ظاهر منفصلًا. السداد المؤكد فقط يخفض المستحق.|Gelecek dönemler bugün dahil, gecikmişler hariçtir. Yalnız onaylı ödemeler kalan tutarı azaltır.|Upcoming windows include today and exclude overdue amounts, which appear separately. Only confirmed payments reduce a due.|Les périodes futures incluent aujourd’hui et excluent les retards, affichés séparément. Seuls les versements confirmés réduisent une échéance.
intelligenceReview|اقتراحات للمراجعة|İnceleme önerileri|Review suggestions|Suggestions de vérification
intelligenceReviewHint|تشابه الحركات أو كبر المبلغ لا يعني وجود خطأ. راجع الأصل؛ لا يُحذف أو يُعدّل شيء تلقائيًا.|Benzer işlemler veya büyük tutar hata demek değildir. Kaydı inceleyin; hiçbir şey otomatik silinmez veya değişmez.|Similar records or a large amount do not prove an error. Review the originals; nothing is deleted or changed automatically.|Des opérations similaires ou un montant élevé ne prouvent pas une erreur. Vérifiez les originaux ; aucune modification automatique.
intelligenceDuplicate|حركات قد تكون مكررة|Olası yinelenen işlemler|Possible duplicate records|Opérations possiblement en double
intelligenceUnusual|مصروف أعلى من المعتاد|Alışılmışın üzerinde gider|Expense above recent baseline|Dépense supérieure au niveau habituel
intelligenceBaseline|وسيط المصروفات السابقة لنفس العملة والفئة|Aynı para birimi ve kategorideki önceki gider medyanı|Median earlier expenses in the same currency and category|Médiane des dépenses antérieures dans la même devise et catégorie
intelligenceNoReview|لا توجد اقتراحات مراجعة وفق هذه القواعد.|Bu kurallara göre inceleme önerisi yok.|No review suggestions under these rules.|Aucune suggestion selon ces règles.
intelligenceEmpty|أضف حركات أو ميزانية أو خطة أقساط لرؤية نظرتك المالية.|Finansal görünüm için işlem, bütçe veya taksit planı ekleyin.|Add transactions, a budget, or an installment plan to see your overview.|Ajoutez des mouvements, un budget ou un échéancier pour afficher cette vue.
intelligenceOpenLedger|فتح الحركات|Hareketleri aç|Open ledger|Ouvrir les mouvements
intelligenceOpenDues|فتح الأقساط|Taksitleri aç|Open installments|Ouvrir les échéances
intelligenceUnavailable|تعذر حساب النظرة المالية من هذه البيانات.|Bu verilerden finansal görünüm hesaplanamadı.|This financial overview could not be calculated from the current data.|Impossible de calculer cette vue avec les données actuelles.
intelligenceHistory|السجل الشهري المسجل|Kaydedilen aylık geçmiş|Recorded monthly history|Historique mensuel enregistré
intelligenceMonth|الشهر|Ay|Month|Mois
intelligenceCompleteMonth|شهر سابق كامل|Önceki tam ay|Previous full month|Mois précédent entier
intelligencePartialMonth|الشهر الحالي حتى اليوم|Bu ay bugüne kadar|Current month to date|Mois courant à ce jour
intelligenceHistoryHint|آخر 6 أشهر بعملة واحدة. الشهر الحالي غير مكتمل؛ غياب الحركات المسجلة لا يثبت غياب الإنفاق الفعلي.|Son 6 ay aynı para biriminde. Güncel ay eksik; kayıt olmaması gerçek harcama olmadığı anlamına gelmez.|Last 6 calendar months in one currency. The current month is partial; no recorded activity does not prove no actual spending.|Les 6 derniers mois dans une même devise. Le mois courant est partiel ; l’absence d’écritures ne prouve pas l’absence de dépenses réelles.
`);
const t=k=>tr(k),esc=s=>E(s),allowed=()=>!App.locked&&!root.Online?.Workspace?.guest?.()&&!root.Online?.Workspace?.context;
const money=(n,c)=>`<bdi class="${App.prefs.hideNumbers?'blurred':''}">${esc(C.fixedMinor(n,C.digits(c))+' '+(App.assetLabel?.(c)||c))}</bdi>`;
const button=(action,label,extra='')=>`<button type="button" data-intelligence="${action}" ${extra}>${esc(t(label))}</button>`;
const entry=()=>`<section class="panel intelligence-entry"><div><h2>${esc(t('intelligenceTitle'))}</h2><p class="hint">${esc(t('intelligenceHint'))}</p></div>${button('open','intelligenceTitle')}</section>`;
const metric=(label,n,c)=>`<div class="intelligence-metric"><span>${esc(t(label))}</span><strong>${money(n,c)}</strong></div>`;
const UI=root.MasarifiOverview={
 available:allowed,
 read(){if(!allowed())throw Error('intelligencePrivate');const rows=App.financialRows?App.financialRows():App.rows,earliest=rows.filter(r=>(!App.filter.accountId||App.filter.accountId==='all'||r.accountId===App.filter.accountId)&&(!App.filter.currency||App.filter.currency==='all'||r.currency===App.filter.currency)).map(r=>r.date?.slice(0,10)).filter(d=>I.validDay(d)&&d<=C.day()).sort()[0];const result=I.analyze({rows,accounts:App.accounts.map(a=>({...a,accountId:a.id})),installments:App.installments||[],budgets:App.prefs.budget||{}},{today:C.day(),section:App.prefs.section,from:App.filter.from||earliest||'',to:App.filter.to||'',accountId:App.filter.accountId||'all',currency:App.filter.currency||'all'});for(const c of result.currencies){let balance=0;for(const a of App.accounts.filter(a=>a.currency===c.currency&&(!App.filter.accountId||App.filter.accountId==='all'||a.id===App.filter.accountId)))balance=C.safeAdd(balance,App.accountStats(a,{to:result.period.to}).closing);c.balance=balance;}return result;},
 page(){if(!allowed())return `<section class="panel"><p>${esc(t('intelligencePrivate'))}</p></section>`;let report;try{report=this.read();}catch(error){return `<section class="panel" role="alert"><p>${esc(t('intelligenceUnavailable'))}</p><p>${esc(t(error.message==='overflow'?'overflow':'invalidBackup'))}</p></section>`;}
  return `<div class="stack intelligence-page"><section class="panel intelligence-hero"><span class="eyebrow">${esc(t(App.prefs.section))}</span><span class="v87-financial-icon" aria-hidden="true">${ico('net')}</span><p>${esc(t('intelligenceHint'))}</p><p class="hint">${esc(t('intelligenceLocal'))}</p><div class="row">${button('records','intelligenceOpenLedger')}${button('installments','intelligenceOpenDues')}</div></section><section class="panel"><h2>${esc(t(report.period.custom?'v87SelectedPeriod':'intelligencePeriod'))}</h2><p><bdi>${esc(report.period.from)} — ${esc(report.period.to)}</bdi></p><p class="hint">${esc(t('intelligencePrior'))}: <bdi>${esc(report.period.priorFrom)} — ${esc(report.period.priorTo)}</bdi></p><details class="intelligence-scope-help"><summary>${esc(t('details'))}</summary><p class="hint">${esc(t(report.period.custom?'v87PriorPeriod':'intelligenceComparison'))}</p><p class="hint">${esc(t('intelligenceScope'))}</p></details></section>${report.currencies.map(c=>this.currencyCard(c)).join('')||`<section class="panel intelligence-empty"><p>${esc(t('intelligenceEmpty'))}</p>${button('records','intelligenceOpenLedger')}</section>`}${this.review(report)}</div>`;
 },
 currencyCard(c){const change=c.change.expenseBasisPoints,percent=change==null?esc(t('intelligenceNoPrior')):`<bdi class="${App.prefs.hideNumbers?'blurred':''}">${change>0?'+':''}${esc(C.fixedMinor(change,2))}%</bdi>`,duesRows=['payable','receivable'].map(direction=>`<tr><th scope="row">${esc(t(direction==='payable'?'v22Payable':'v22Receivable'))}</th><td>${money(c.dues[direction].overdue,c.currency)}</td><td>${money(c.dues[direction].next7,c.currency)}</td><td>${money(c.dues[direction].next30,c.currency)}</td></tr>`).join('');
  const categories=c.categories.slice(0,8).map(x=>`<tr><th scope="row">${esc(App.category?.(x.category)||x.category||t(x.type))}<small>${esc(t(x.type))}</small></th><td>${money(x.currentMinor,c.currency)}</td><td>${money(x.priorMinor,c.currency)}</td><td>${money(x.deltaMinor,c.currency)}</td></tr>`).join('');
  const budget=c.budget?`<section class="intelligence-subsection"><h3>${esc(t('intelligenceBudget'))}</h3><div class="intelligence-metrics">${metric('intelligenceBudgetLimit',c.budget.limitMinor,c.currency)}${metric('budgetRemaining',c.budget.remainingMinor,c.currency)}${metric('intelligenceExpected',c.budget.expectedByTodayMinor,c.currency)}</div>${!App.prefs.hideNumbers?`<progress max="10000" value="${Math.min(10000,c.budget.usedBasisPoints??10000)}" aria-label="${esc(t('intelligenceBudget'))}"></progress>`:''}<p class="hint">${esc(t(c.budget.pace==='over'?'intelligencePaceOver':'intelligencePaceWithin'))}</p></section>`:'';
  return `<article class="panel intelligence-currency"><h2><bdi>${esc(App.assetLabel?.(c.currency)||c.currency)}</bdi></h2><div class="intelligence-metrics">${metric('incomeTotal',c.current.income,c.currency)}${metric('expenseTotal',c.current.expense,c.currency)}${metric('net',c.current.net,c.currency)}</div><div class="v87-balance-summary"><span>${esc(t('v87CashBalance'))}</span><strong>${money(c.balance,c.currency)}</strong></div><p class="hint">${esc(t('v87NetHint'))}</p><div class="intelligence-change"><span>${esc(t('intelligenceExpenseChange'))}</span>${money(c.change.expenseMinor,c.currency)} ${percent}</div><details class="intelligence-details"><summary>${esc(t('details'))}</summary>${this.history(c)}${categories?`<section class="intelligence-subsection"><h3>${esc(t('intelligenceCategories'))}</h3><p class="hint">${esc(t('intelligenceCategoryHint'))}</p><div class="intelligence-table-wrap"><table><thead><tr><th scope="col">${esc(t('category'))}</th><th scope="col">${esc(t('intelligencePeriod'))}</th><th scope="col">${esc(t('intelligencePrior'))}</th><th scope="col">${esc(t('net'))}</th></tr></thead><tbody>${categories}</tbody></table></div></section>`:''}${budget}<section class="intelligence-subsection" ${c.projection.status==='not-applicable'?'hidden':''}><h3>${esc(t('intelligenceForecast'))}</h3>${c.projection.status==='estimate'?`<strong class="intelligence-estimate">${money(c.projection.expenseMinor,c.currency)}</strong>`:`<p class="hint">${esc(t(c.projection.reason==='overflow'?'intelligenceEstimateOverflow':'intelligenceInsufficient'))}</p>`}<p class="hint">${esc(t('intelligenceForecastHint'))}</p></section><section class="intelligence-subsection"><h3>${esc(t('intelligenceDues'))}</h3><div class="intelligence-table-wrap"><table><thead><tr><th scope="col">${esc(t('type'))}</th><th scope="col">${esc(t('v22Overdue'))}</th><th scope="col">${esc(t('intelligenceNext7'))}</th><th scope="col">${esc(t('intelligenceNext30'))}</th></tr></thead><tbody>${duesRows}</tbody></table></div><p class="hint">${esc(t('intelligenceDueHint'))}</p></section></details></article>`;
 },
 history(c){if(!Array.isArray(c.history))return'';return `<section class="intelligence-subsection intelligence-history"><h3>${esc(t('intelligenceHistory'))}</h3><p class="hint">${esc(t('intelligenceHistoryHint'))}</p><div class="intelligence-table-wrap"><table><thead><tr><th scope="col">${esc(t('intelligenceMonth'))}</th><th scope="col">${esc(t('incomeTotal'))}</th><th scope="col">${esc(t('expenseTotal'))}</th><th scope="col">${esc(t('net'))}</th></tr></thead><tbody>${c.history.map(h=>`<tr class="${h.complete?'':'intelligence-partial-month'}"><th scope="row"><bdi>${esc(h.month)}</bdi><small>${esc(t(h.complete?'intelligenceCompleteMonth':'intelligencePartialMonth'))}</small></th><td>${money(h.income,c.currency)}</td><td>${money(h.expense,c.currency)}</td><td>${money(h.net,c.currency)}</td></tr>`).join('')}</tbody></table></div></section>`;},
 review(report){const items=[];for(const d of report.review.duplicates.slice(0,10)){const r=App.rows.find(r=>r.id===d.ids[0]);items.push(`<li><strong>${esc(t('intelligenceDuplicate'))}</strong><p>${esc(r?.description||d.date)} · ${money(d.minor,d.currency)} <span class="badge">${d.ids.length}</span></p><div class="row">${d.ids.slice(0,5).map(id=>button('row','details',`data-id="${esc(id)}"`)).join('')}</div></li>`);}for(const u of report.review.unusual.slice(0,10)){const r=App.rows.find(r=>r.id===u.id);items.push(`<li><strong>${esc(t('intelligenceUnusual'))}</strong><p>${esc(r?.description||'')} · ${money(u.minor,u.currency)}</p><p class="hint">${esc(t('intelligenceBaseline'))}: ${money(u.baselineMinor,u.currency)}</p>${button('row','details',`data-id="${esc(u.id)}"`)}</li>`);}return `<details class="panel intelligence-review"><summary>${esc(t('intelligenceReview'))}</summary><p class="hint">${esc(t('intelligenceReviewHint'))}</p>${items.length?`<ul>${items.join('')}</ul>`:`<p>${esc(t('intelligenceNoReview'))}</p>`}</details>`;}
};
V6.routes.add('intelligence');V7.pages.intelligence=()=>UI.page();const title=V7.title;V7.title=function(){return App.page==='intelligence'?t('intelligenceTitle'):title.apply(this,arguments);};const navSlot=V7.navSlot;V7.navSlot=function(){return App.page==='intelligence'?4:navSlot.apply(this,arguments);};
const home=App.home;App.home=function(){const html=home.apply(this,arguments);return allowed()?html+entry():html;};const settings=App.settingsPage;App.settingsPage=function(){const html=settings.apply(this,arguments);return allowed()&&!V6.settingsSection?html+entry():html;};
if(root.V17User?.menu){const menu=root.V17User.menu;root.V17User.menu=function(group){const result=menu.apply(this,arguments);if(allowed()&&group==='activity'){const host=document.querySelector('#v16NavMenu .v16-menu-grid');if(host&&!host.querySelector('[data-intelligence]'))host.insertAdjacentHTML('beforeend',`<button type="button" class="quick-item" data-intelligence="open"><span aria-hidden="true">${ico('net')}</span><strong>${esc(t('intelligenceTitle'))}</strong>${ico('arrow')}</button>`);}return result;};}
document.addEventListener('click',e=>{const b=e.target.closest('[data-intelligence]');if(!b)return;e.preventDefault();if(!allowed())return;try{const action=b.dataset.intelligence;if(action==='row'){const row=App.rows.find(r=>r.id===b.dataset.id&&r.section===App.prefs.section);if(row)App.rowDetails(row.id);return;}const page={open:'intelligence',records:'records',installments:'installments'}[action];if(!page)return;const dialog=b.closest('dialog');if(dialog?.open)dialog.close();V7.navigate(page);}catch(error){App.error(error);}});
})(window);
