/* Compatible category and budget persistence, with section-bound projections and atomic rules. */
(function(root,factory){'use strict';const api=factory();if(typeof module==='object'&&module.exports)module.exports=api;if(root.App&&root.PlanningCore&&root.SectionPreferences)api.install(root,{DB:typeof DB==='undefined'?root.DB:DB});})(typeof window==='undefined'?globalThis:window,function(){'use strict';
const own=(v,k)=>Object.prototype.hasOwnProperty.call(v||{},k),empty=()=>({version:1,items:[]});
function install(root,globals={}){
 if(root.MasarifiPlanning)return root.MasarifiPlanning;const A=root.App,C=root.Core,DB=globals.DB||root.DB,S=root.SectionPreferences,K=root.PlanningCore.create({Core:C,Bank:root.Bank});if(!DB||!S)throw Error('v86BudgetInvalid');
 const uuid=()=>root.crypto?.randomUUID?.()||'plan-'+Date.now().toString(36)+'-'+Math.random().toString(36).slice(2),now=()=>new Date().toISOString(),budgets=()=>A.prefs.planningBudgets||empty(),proof=()=>S.proof();
 const authorized=section=>!A.locked&&section===A.prefs.section&&S.allowed(section),assert=p=>{if(!S.current(p))throw Error('v85SectionLocked');},rawRows=()=>A.financialRows?.()||A.rows||[];
 const label=c=>c?.labels?.[A.prefs.language]||c?.labels?.en||c?.labels?.ar||c?.id||'';
 root.V6?.addLabels?.(`
v86CategoryInvalid|راجع اسم التصنيف وأيقونته ولونه.|Kategori adını, simgesini ve rengini kontrol edin.|Check the category name, icon and color.|Vérifiez le nom, l’icône et la couleur.
v86CategoryCycle|لا يمكن أن يكون التصنيف فرعًا من نفسه أو من أحد فروعه.|Kategori kendisinin veya alt kategorisinin altına taşınamaz.|A category cannot be placed under itself or a descendant.|Une catégorie ne peut dépendre d’elle-même ni de ses descendants.
v86CategoryParent|اختر تصنيفًا رئيسيًا من نفس النوع.|Aynı türden bir üst kategori seçin.|Choose a parent category of the same type.|Choisissez une catégorie parente du même type.
v86CategoryDepth|يمكن ترتيب التصنيفات حتى 8 مستويات.|Kategoriler en fazla 8 düzey olabilir.|Categories support up to 8 levels.|Les catégories permettent jusqu’à 8 niveaux.
v86CategoryLimit|يمكن إضافة حتى 200 تصنيف؛ أرشف التصنيفات غير اللازمة.|En fazla 200 kategori eklenebilir; kullanılmayanları arşivleyin.|You can add up to 200 categories; archive unused ones.|Vous pouvez ajouter jusqu’à 200 catégories ; archivez celles inutilisées.
v86BudgetInvalid|راجع العملة والمبلغ والشهر والتصنيف وحد التنبيه.|Para birimini, tutarı, ayı, kategoriyi ve uyarı eşiğini kontrol edin.|Check the currency, amount, month, category and warning threshold.|Vérifiez la devise, le montant, le mois, la catégorie et le seuil.
v86BudgetDuplicate|يوجد حد لهذا التصنيف والعملة والفترة؛ عدّل الحد الموجود.|Bu kategori, para birimi ve dönem için bir limit var; mevcut limiti düzenleyin.|A limit already exists for this category, currency and period; edit it.|Un plafond existe déjà pour cette catégorie, devise et période ; modifiez-le.
v86PlanningFees|رسوم التحويل والبنك|Transfer ve banka ücretleri|Transfer and bank fees|Frais de transfert et bancaires
v86PlanningUncategorized|تصنيفات قديمة غير متاحة|Eski, kullanılamayan kategoriler|Unavailable legacy categories|Anciennes catégories indisponibles
`);
 const previousPrefs=root.safePrefs;if(previousPrefs)root.safePrefs=function(raw,defaults){const out=previousPrefs(raw,defaults),saved=own(raw,'planningBudgets')?raw.planningBudgets:defaults?.planningBudgets;if(saved!==undefined)out.planningBudgets=K.normalizeBudgets(saved,A.categories||[],{allowMissingCategories:true,allowDuplicateScopes:true});else out.planningBudgets=empty();return out;};
 const previousValidate=root.validateBundle;if(previousValidate)root.validateBundle=function(raw){const out=previousValidate(raw);if(out.categories)K.validateCategories(out.categories);if(own(out.prefs,'planningBudgets'))out.prefs={...out.prefs,planningBudgets:K.normalizeBudgets(out.prefs.planningBudgets,out.categories||[])};return out;};
 function allRules(raw=budgets(),legacy=A.prefs.budget||{}){const out=K.normalizeBudgets(raw,A.categories||[],{allowMissingCategories:true,allowDuplicateScopes:true}),items=[...out.items];for(const[scope,limitMinor]of Object.entries(legacy)){const split=scope.split(':'),section=split[0],currency=split[1];if(!['personal','work'].includes(section)||!C.currencies.includes(currency)||!Number.isSafeInteger(limitMinor)||limitMinor<=0||items.some(r=>r.section===section&&r.currency===currency&&r.categoryId===null&&r.period==='monthly'))continue;items.push({id:'legacy:'+section+':'+currency,section,currency,categoryId:null,period:'monthly',limitMinor,warningPercent:80,includeDescendants:true,rev:1,updatedAt:'2000-01-01T00:00:00',legacy:true});}return{version:1,items};}
 function financialOptions(options={}){const section=options.section||A.prefs.section,currency=options.currency||(section==='work'?A.prefs.currencyWork:A.prefs.currencyPersonal),today=options.today||C.day(),month=options.month||today.slice(0,7);return{section,currency,today,month,authorized:authorized(section)};}
 const restricted=o=>({restricted:true,section:o.section,currency:o.currency,month:o.month,today:o.today,currencies:[],rowCount:0,totalMinor:0n,previousMinor:0n,comparisonPercent:null,feesMinor:0n,unbudgetedMinor:0n,categories:[],budgets:[],categoryRules:[],overall:null,issues:[]});
 function periods(options,type='expense'){const o=financialOptions(options);if(!o.authorized)return{o,restricted:true};if(!C.currencies.includes(o.currency))throw Error('v86BudgetInvalid');const ranges=K.monthRanges(o.month,o.today),input={rows:rawRows(),categories:A.categories},current=K.spending(input,{...o,...ranges.range,type}),previous=K.spending(input,{...o,...ranges.previousRange,type});return{o,...ranges,current,previous};}
 function model(options={}){
  const p=periods(options);if(p.restricted)return restricted(p.o);const{o,current,previous,range,previousRange}=p,prev=new Map(previous.categories.map(c=>[c.id,c])),rules=K.effectiveBudgets(allRules(),o,A.categories),rows=K.eligibleRows(rawRows(),{...o,...range,type:'expense'}),covered=new Set();
  const entry=r=>{const ids=r.categoryId===null?null:new Set(r.categoryId==='__fees__'?['__fees__']:r.includeDescendants?K.descendants(r.categoryId,A.categories):[r.categoryId]);let spent=0n,prior=0n,count=0;for(const c of current.categories)if(!ids||ids.has(c.id)){spent+=c.directMinor;count+=c.count;if(ids)covered.add(c.id);}for(const c of previous.categories)if(!ids||ids.has(c.id))prior+=c.directMinor;const result=K.budgetStatus(r,spent,prior,count);if(r.legacy)result.rev=0;return result;};
  const budgetRows=rules.map(entry),categories=current.categories.map(c=>({...c,label:c.id==='__fees__'?root.tr('v86PlanningFees'):c.id==='__uncategorized__'?root.tr('v86PlanningUncategorized'):label(c.category),previousMinor:prev.get(c.id)?.directMinor||0n,comparisonPercent:(prev.get(c.id)?.directMinor||0n)>0n?K.percent(c.directMinor-(prev.get(c.id)?.directMinor||0n),prev.get(c.id).directMinor):null}));
  const currencies=new Set([o.currency]);for(const r of K.eligibleRows(rawRows(),{section:o.section,today:o.today,authorized:true}))currencies.add(r.currency);for(const r of allRules().items)if(!r.deleted&&r.section===o.section)currencies.add(r.currency);for(const a of A.accounts||[])if(C.currencies.includes(a.currency))currencies.add(a.currency);
  const comparisonPercent=previous.totalMinor>0n?K.percent(current.totalMinor-previous.totalMinor,previous.totalMinor):null,unbudgetedMinor=current.categories.reduce((sum,c)=>sum+(covered.has(c.id)?0n:c.directMinor),0n);
  return{restricted:false,...o,range,previousRange,currencies:[...currencies],rowCount:rows.length,totalMinor:current.totalMinor,previousMinor:previous.totalMinor,comparisonPercent,feesMinor:current.feesMinor,unbudgetedMinor,categories,budgets:budgetRows,categoryRules:budgetRows.filter(r=>r.categoryId!==null),overall:budgetRows.find(r=>r.categoryId===null)||null,issues:current.issues,comparison:{currentMinor:current.totalMinor,previousMinor:previous.totalMinor,deltaMinor:current.totalMinor-previous.totalMinor,percentage:comparisonPercent}};
 }
 function statValue(categoryId,cat,p,includeChildren=true){if(p.restricted)return{...restricted(p.o),directMinor:0n,count:0,sharePercent:0,meta:K.meta(cat)};const a=p.current.categories.find(c=>c.id===categoryId),b=p.previous.categories.find(c=>c.id===categoryId),direct=a?.directMinor||0n,total=includeChildren?a?.totalMinor||0n:direct,prior=includeChildren?b?.totalMinor||0n:b?.directMinor||0n,count=includeChildren?a?.totalCount||0:a?.count||0;return{restricted:false,...p.o,directMinor:direct,totalMinor:total,previousMinor:prior,count,sharePercent:K.percent(total,p.current.totalMinor),directSharePercent:K.percent(direct,p.current.totalMinor),comparisonPercent:prior?K.percent(total-prior,prior):null,meta:a?.meta||K.meta(cat)};}
 function stats(categoryId,options={}){const cat=A.categories.find(c=>c.id===categoryId),p=periods(options,cat?.type||'expense');return statValue(categoryId,cat,p,options.includeChildren!==false);}
 function statsAll(options={}){const type=options.type||'expense',p=periods(options,type),out=new Map();if(p.restricted)return out;for(const cat of A.categories||[])if(!cat.deleted&&cat.type===type)out.set(cat.id,statValue(cat.id,cat,p,options.includeChildren!==false));return out;}

 const activeItems=()=>K.catalog(A.categories||[]).items.filter(c=>!c.deleted);
 function list(options={}){if(!authorized(A.prefs.section))return[];const query=C.normalize(options.search||'');return activeItems().filter(c=>(!options.type||c.type===options.type)&&(options.includeArchived||!c.meta.archived)&&(!query||C.normalize(Object.values(c.labels||{}).join(' ')).includes(query)));}
 const eligible=(type,options={})=>list({type,includeArchived:true}).filter(c=>!c.meta.archived||c.id===options.existingId);
 function usage(categoryId){const allowed=authorized(A.prefs.section),section=A.prefs.section,allTransactions=A.rows||[],trash=A.trash||[],examples=A.examples||[],plans=A.installments||[],items=budgets().items||[],children=activeItems().filter(c=>c.meta.parentId===categoryId),shared=[...(root.Online?.snapshots?.values?.()||[])].some(s=>(s.entries||[]).some(e=>!e.deleted&&e.payload?.category===categoryId)),anyTx=allTransactions.some(r=>r.category===categoryId),anyTrash=trash.some(t=>t.record?.category===categoryId),anyExamples=examples.some(e=>e.category===categoryId),anyPlans=plans.some(p=>p.status!=='deleted'&&p.category===categoryId),anyBudgets=items.some(r=>!r.deleted&&r.categoryId===categoryId);const used=anyTx||anyTrash||anyExamples||anyPlans||shared;return{transactions:allowed?allTransactions.filter(r=>r.section===section&&r.category===categoryId).length:0,trash:allowed?trash.filter(t=>t.record?.section===section&&t.record.category===categoryId).length:0,examples:allowed?examples.filter(e=>e.category===categoryId).length:0,installments:allowed?plans.filter(p=>p.section===section&&p.status!=='deleted'&&p.category===categoryId).length:0,budgets:allowed?items.filter(r=>!r.deleted&&r.section===section&&r.categoryId===categoryId).length:0,children:allowed?children.length:0,used,blocked:used||children.length>0||anyBudgets};}
 const budgetIntent=Symbol('planningBudgetWrite');
 const lockSignature=value=>value?JSON.stringify([value.hash,value.salt,value.kind,value.version,value.algorithm,value.iterations]):'';
 const assertStored=(p,prefs)=>{assert(p);if(p.signature!==undefined&&lockSignature(prefs?.sectionLocks?.[p.section])!==p.signature)throw Error('v85SectionLocked');};
 function mirrorLegacy(value,planning){const legacy={...(value.budget||{})},scopes=new Set(planning.items.filter(r=>r.categoryId===null&&r.period==='monthly').map(r=>r.section+':'+r.currency));for(const key of scopes){const[section,currency]=key.split(':'),rules=K.effectiveBudgets({version:1,items:planning.items.filter(r=>r.period==='monthly')},{section,currency,month:C.day().slice(0,7)},A.categories),monthly=rules.find(r=>r.categoryId===null&&r.period==='monthly');legacy[key]=monthly?.limitMinor||0;}return legacy;}
 const priorPrepare=S.preparePreferenceWrite;S.preparePreferenceWrite=function(op,stored){priorPrepare?.call(this,op,stored);if(op.store!=='meta'||op.value?.id!=='prefs')return;const intent=op[budgetIntent],latest=stored?.value||{};if(intent){assert(intent.proof);const config=K.normalizeBudgets(latest.planningBudgets||empty(),A.categories,{allowMissingCategories:true,allowDuplicateScopes:true}),old=config.items.find(r=>r.id===intent.rule.id);if((old?.rev||0)!==intent.expected)throw Error('conflict');if(!intent.rule.deleted&&config.items.some(r=>!r.deleted&&r.id!==intent.rule.id&&K.scope(r)===K.scope(intent.rule)))throw Error('v86BudgetDuplicate');const merged={version:1,items:[...config.items.filter(r=>r.id!==intent.rule.id),...(intent.retired?[intent.retired]:[]),intent.rule]};K.normalizeBudgets(merged,A.categories);op.value.value={...latest,planningBudgets:merged,budget:mirrorLegacy(latest,merged)};assertStored(intent.proof,latest);}else{op.value.value.planningBudgets=K.normalizeBudgets(latest.planningBudgets||op.value.value.planningBudgets||empty(),A.categories,{allowMissingCategories:true,allowDuplicateScopes:true});op.value.value.budget=mirrorLegacy(op.value.value,op.value.value.planningBudgets);}};
 async function writeBudget(input,expected,p,deleting=false){assert(p);if(input.section!==p.section)throw Error('v85SectionScope');const saved=(await DB.get('meta','prefs'))?.value||A.prefs;assert(p);const stored=K.normalizeBudgets(saved.planningBudgets||empty(),A.categories,{allowMissingCategories:true,allowDuplicateScopes:true}),old=stored.items.find(r=>r.id===input.id);if((old?.rev||0)!==expected)throw Error('conflict');const record={...input,id:input.id||uuid(),section:p.section,categoryId:input.categoryId||null,includeDescendants:input.includeDescendants!==false,rev:expected+1,updatedAt:now(),...(deleting?{deleted:true}:{deleted:false})};delete record.legacy;const previousScope=old||allRules(stored,saved.budget||{}).items.find(r=>r.id===input.id&&r.legacy),retired=previousScope&&K.scope(previousScope)!==K.scope(record)?{...previousScope,id:'retired-'+uuid(),rev:1,updatedAt:record.updatedAt,deleted:true}:null;if(retired)delete retired.legacy;const config={version:1,items:[...stored.items.filter(r=>r.id!==record.id),...(retired?[retired]:[]),record]};K.normalizeBudgets(config,A.categories);const op={store:'meta',value:{id:'prefs',value:{...saved,planningBudgets:config}},[budgetIntent]:{rule:record,retired,expected,proof:p}};const category=record.categoryId&&record.categoryId!=='__fees__'?A.categories.find(c=>c.id===record.categoryId&&!c.deleted):null;const ops=category?[{store:'categories',value:structuredClone(category),expected:category.rev||0},op]:[op];await DB.commit(S.scopeOperations(p,ops));assert(p);A.prefs={...A.prefs,planningBudgets:structuredClone(op.value.value.planningBudgets),budget:structuredClone(op.value.value.budget)};A.invalidateReport?.();A.channel?.postMessage('changed');root.dispatchEvent?.(new root.CustomEvent('masarifi:planning-changed',{detail:{kind:'budget',section:p.section}}));return record;}
 const saveBudget=(input,expected=0,p=proof())=>writeBudget(input,expected,p);
 async function deleteBudget(ruleId,expected,p=proof()){assert(p);const current=allRules().items.find(r=>r.id===ruleId);if(!current||current.deleted)throw Error('conflict');if(current.legacy)current.rev=0;return writeBudget(current,expected??current.rev,p,true);}
 function cleanCategory(input,old){if(!input||!['expense','income'].includes(input.type)||old&&old.type!==input.type)throw Error('v86CategoryInvalid');const labels={};for(const lang of ['ar','tr','en','fr']){const value=input.labels?.[lang];if(typeof value!=='string'||!value.trim()||Array.from(value.trim()).length>100||/[\x00-\x1f\x7f-\x9f\u202a-\u202e\u2066-\u2069]/u.test(value))throw Error('v86CategoryInvalid');labels[lang]=value.trim().normalize('NFC');}return{...(old||{}),...input,labels,parentId:input.parentId||null,icon:input.icon||K.meta(old||input).icon,color:input.color||K.meta(old||input).color,pinned:input.pinned===true,archived:input.archived===true,order:input.order??old?.order??0,deleted:false};}
 function checkCategoryWrite(input,expected,categories,deleting,refs={},prefs=A.prefs){const old=categories.find(c=>c.id===input.id);if((old?.rev||0)!==expected||old?.deleted)throw Error('conflict');if(deleting){if(!old)throw Error('conflict');const fullBudget=K.normalizeBudgets(prefs.planningBudgets||empty(),categories,{allowMissingCategories:true,allowDuplicateScopes:true}).items;const inUse=(refs.transactions||[]).some(r=>r.category===old.id)||(refs.trash||[]).some(t=>t.record?.category===old.id)||(refs.examples||[]).some(r=>r.category===old.id)||(refs.installments||[]).some(r=>r.status!=='deleted'&&r.category===old.id)||categories.some(c=>!c.deleted&&c.parentId===old.id)||fullBudget.some(r=>!r.deleted&&r.categoryId===old.id)||[...(root.Online?.snapshots?.values?.()||[])].some(s=>(s.entries||[]).some(e=>!e.deleted&&e.payload?.category===old.id));if(inUse)throw Error('categoryInUse');return{...old,deleted:true,archived:true,rev:expected+1,updatedAt:now()};}if(!old&&categories.filter(c=>!c.deleted).length>=200)throw Error('v86CategoryLimit');const record=cleanCategory(input,old);for(const c of categories){if(c.deleted||c.id===record.id||c.type!==record.type)continue;if(Object.values(c.labels||{}).some(v=>Object.values(record.labels).some(n=>C.normalize(n)===C.normalize(v))))throw Error('duplicateName');}record.rev=expected+1;record.updatedAt=now();K.validateCategories([...categories.filter(c=>c.id!==record.id),record]);return record;}
 function categoryMove(input,categories){const selected=categories.find(c=>c.id===input.id&&!c.deleted);if(!selected||(selected.rev||0)!==input.expected)throw Error('conflict');const siblings=K.catalog(categories).items.filter(c=>!c.deleted&&c.type===selected.type&&(c.meta.parentId||null)===(K.meta(selected).parentId||null)),at=siblings.findIndex(c=>c.id===selected.id),next=at+(input.moveDirection==='up'?-1:1);if(next<0||next>=siblings.length)return{records:[],target:selected};[siblings[at],siblings[next]]=[siblings[next],siblings[at]];const records=siblings.map((c,index)=>{const {meta,...original}=c;return{...original,order:index,rev:(c.rev||0)+1,updatedAt:now()};});return{records,target:records.find(c=>c.id===selected.id)};}
 async function categoryWrite(input,expected,p,deleting){assert(p);input={...input,id:input.id||uuid(),...(input.moveDirection?{expected}: {})};let result;
  if(DB.db?.transaction){await new Promise((resolve,reject)=>{const wanted=deleting?['categories','transactions','trash','examples','installments','meta']:['categories','meta'],stores=wanted.filter(name=>!DB.db.objectStoreNames||DB.db.objectStoreNames.contains(name)),tx=DB.db.transaction(stores,'readwrite'),values={},requests=[];let failure,remaining=stores.length;tx.oncomplete=resolve;tx.onerror=tx.onabort=()=>reject(failure||tx.error||Error('storageError'));const finish=()=>{if(--remaining)return;try{assert(p);const prefs=(values.meta||[]).find(v=>v.id==='prefs')?.value||A.prefs;assertStored(p,prefs);const change=input.moveDirection?categoryMove(input,values.categories||[]):{records:[checkCategoryWrite(input,expected,values.categories||[],deleting,values,prefs)]};result=change.target||change.records[0];assertStored(p,prefs);for(const record of change.records)tx.objectStore('categories').put(record);if(change.records.length)tx.objectStore('meta').put({id:'v9PrivateDirty',value:uuid()});}catch(error){failure=error;tx.abort();}};for(const name of stores){const request=tx.objectStore(name).getAll();requests.push(request);request.onsuccess=()=>{values[name]=request.result;finish();};}});
  }else{const categories=await DB.all('categories'),refs={};for(const name of ['transactions','trash','examples','installments'])refs[name]=await DB.all(name);const prefs=(await DB.get('meta','prefs'))?.value||A.prefs;assertStored(p,prefs);const change=input.moveDirection?categoryMove(input,categories):{records:[checkCategoryWrite(input,expected,categories,deleting,refs,prefs)]};result=change.target||change.records[0];await DB.commit(S.scopeOperations(p,change.records.map(record=>({store:'categories',value:record,expected:categories.find(c=>c.id===record.id)?.rev||0}))));}
  assert(p);await A.load?.();assert(p);A.invalidateReport?.();A.channel?.postMessage('changed');if(root.Online?.user)root.Online.schedule?.();root.dispatchEvent?.(new root.CustomEvent('masarifi:planning-changed',{detail:{kind:'category',section:p.section}}));return result;
 }
 const moveCategory=(categoryId,direction,p=proof())=>{if(!['up','down'].includes(direction))throw Error('v86CategoryInvalid');return categoryWrite({id:categoryId,moveDirection:direction},A.categories.find(c=>c.id===categoryId)?.rev||0,p,false);};
 const saveCategory=(input,expected=0,p=proof())=>categoryWrite(input,expected,p,false),deleteCategory=(categoryId,expected,p=proof())=>categoryWrite({id:categoryId},expected??A.categories.find(c=>c.id===categoryId)?.rev??0,p,true);
 const O=root.OnlineCore;if(O?.mergePrivate){const original=O.mergePrivate;O.mergePrivate=function(local,remote){const out=original(local,remote),normalized=K.catalog(out.categories||[]),map=new Map(normalized.items.map(c=>[c.id,c.meta.parentId]));out.categories=(out.categories||[]).map(c=>c.parentId&&map.get(c.id)!==c.parentId?{...c,parentId:map.get(c.id)||null}:c);const merged=K.mergeBudgets(local.prefs?.planningBudgets,remote.prefs?.planningBudgets,out.categories),cats=new Map(out.categories.map(c=>[c.id,c]));for(const r of merged.items)if(!r.deleted&&r.categoryId&&r.categoryId!=='__fees__'&&(!cats.get(r.categoryId)||cats.get(r.categoryId).deleted||cats.get(r.categoryId).type!=='expense')){r.deleted=true;r._planningConflict=true;}out.prefs={...out.prefs,planningBudgets:merged};out.prefs.budget=mirrorLegacy(out.prefs,merged);return out;};}
 const family=root.Online?.FamilyUI;if(family?.metadata){const original=family.metadata;family.metadata=function(){const before=A.categories;A.categories=before.filter(c=>!c.deleted);try{return original.apply(this,arguments);}finally{A.categories=before;}};}
 let loadSerial=0;const originalLoad=A.load;if(originalLoad)A.load=async function(){const serial=++loadSerial,result=await originalLoad.apply(this,arguments),record=(await DB.get('meta','prefs'))?.value;if(serial===loadSerial&&record){this.prefs.planningBudgets=K.normalizeBudgets(record.planningBudgets||empty(),this.categories||[],{allowMissingCategories:true,allowDuplicateScopes:true});this.prefs.budget={};for(const[key,value]of Object.entries(record.budget||{})){const[section,currency]=key.split(':');if(['personal','work'].includes(section)&&C.currencies.includes(currency)&&Number.isSafeInteger(value)&&value>=0)this.prefs.budget[key]=value;}}return result;};
 const P=root.MasarifiPlanning={core:K,icons:K.icons,colors:K.colors,proof,meta(c){const item=typeof c==='string'?A.categories.find(x=>x.id===c):c;return K.catalog(A.categories||[]).items.find(x=>x.id===item?.id)?.meta||K.meta(item);},list,eligible,usage,stats,statsAll,model,saveCategory,deleteCategory,moveCategory,saveBudget,deleteBudget};return P;
}
return{install};
});
