/* Native-currency category planning. Pure projections never alter the financial ledger. */
(function(root,factory){'use strict';const api=factory({});if(typeof module==='object'&&module.exports)module.exports=api;else root.PlanningCore=api;})(typeof globalThis==='undefined'?this:globalThis,function factory(deps){'use strict';
const ICONS=Object.freeze({...{"coffee":"☕","groceries":"🥬","fuel":"⛽","rent":"🔑","electricity":"💡","water":"💧","internet":"🌐","phone":"📱","medicine":"💊","dental":"🦷","insurance":"🛡️","maintenance":"🔧","clothing":"👕","beauty":"🪞","children":"🧸","family":"👨‍👩‍👧","pet":"🐾","travel":"✈️","hotel":"🏨","sport":"🏃","entertainment":"🎬","books":"📚","subscriptions":"🔁","gift":"🎁","charity":"🤲","taxes":"🏛️","fees":"💳","office":"🖨️","tools":"🧰","delivery":"📦","parking":"🅿️","publictransport":"🚌","freelance":"💻","bonus":"🏅","pension":"🧓","refund":"↩️","sales":"🏪","bike":"🚲","train":"🚆","boat":"⛵","flight":"🛫","camera":"📷","music":"🎵","game":"🎮","garden":"🌱","furniture":"🛋️","laundry":"🧺","bakery":"🥐","fruit":"🍎","restaurant":"🍲","baby":"🍼","wedding":"💍","legal":"⚖️","construction":"🏗️","security":"🔒","repair":"🪛","heating":"🌡️"},tag:'🏷️',food:'🍽️',coffee:'☕',cart:'🛒',transport:'🚗',fuel:'⛽',home:'🏠',health:'🩺',medicine:'💊',education:'🎓',shopping:'🛍️',family:'👨‍👩‍👧',travel:'✈️',sport:'🏃',entertainment:'🎬',gift:'🎁',phone:'📱',bills:'🧾',salary:'💼',business:'🏭',investment:'📈',savings:'🏦',pet:'🐾',fees:'💳',other:'✨'});
const COLORS=Object.freeze(['#64748b','#2563eb','#7c3aed','#db2777','#ea580c','#ca8a04','#0891b2','#dc2626','#475569','#4f46e5','#9333ea','#b45309']);
const STANDARD={food:'food',transport:'transport',home:'home',health:'health',education:'education',shopping:'shopping',salary:'salary',business:'business',investment:'investment','other-expense':'other','other-income':'other'};
const object=v=>v&&typeof v==='object'&&!Array.isArray(v),own=(v,k)=>Object.prototype.hasOwnProperty.call(v||{},k),id=v=>typeof v==='string'&&v.length>0&&v.length<1000&&!/[\x00-\x1f\x7f]/u.test(v);
const canonical=v=>JSON.stringify(v,(_,x)=>object(x)?Object.fromEntries(Object.keys(x).sort().map(k=>[k,x[k]])):x);
function context(){if(!deps.Core)throw Error('v86BudgetInvalid');return deps.Core;}
function meta(c={}){const icon=own(ICONS,c.icon)?c.icon:STANDARD[c.id]||'tag';return{icon,emoji:ICONS[icon],color:COLORS.includes(String(c.color||'').toLowerCase())?String(c.color).toLowerCase():'#64748b',parentId:id(c.parentId)?c.parentId:null,pinned:c.pinned===true,archived:c.archived===true||c.deleted===true,order:Number.isSafeInteger(c.order)&&c.order>=0&&c.order<=1000000?c.order:0,depth:1,issues:[]};}
function validateCategories(categories=[]){
 if(!Array.isArray(categories))throw Error('v86CategoryInvalid');const map=new Map();for(const c of categories){if(!object(c)||!id(c.id)||map.has(c.id)||!['income','expense'].includes(c.type)||!object(c.labels)||!['ar','tr','en'].every(l=>typeof c.labels[l]==='string'))throw Error('v86CategoryInvalid');map.set(c.id,c);if(c.parentId!=null&&c.parentId!==''&&!id(c.parentId)||c.icon!==undefined&&!own(ICONS,c.icon)||c.color!==undefined&&!COLORS.includes(c.color)||c.pinned!==undefined&&typeof c.pinned!=='boolean'||c.archived!==undefined&&typeof c.archived!=='boolean'||c.deleted!==undefined&&typeof c.deleted!=='boolean'||c.order!==undefined&&(!Number.isSafeInteger(c.order)||c.order<0||c.order>1000000))throw Error('v86CategoryInvalid');}
 for(const c of categories){if(c.deleted)continue;let current=c,depth=1,seen=new Set([c.id]);while(current.parentId){const p=map.get(current.parentId);if(!p||p.deleted||p.type!==c.type)throw Error('v86CategoryParent');if(seen.has(p.id))throw Error('v86CategoryCycle');seen.add(p.id);if(++depth>8)throw Error('v86CategoryDepth');current=p;}}
 return categories;
}
function catalog(categories=[]){const map=new Map(),issues=[];for(const c of Array.isArray(categories)?categories:[]){if(!c||!id(c.id)||map.has(c.id)||!['income','expense'].includes(c.type)){issues.push('invalidCategory');continue;}map.set(c.id,{...c,meta:meta(c)});}
 for(const c of [...map.values()].sort((a,b)=>a.id.localeCompare(b.id))){if(c.deleted){c.meta.parentId=null;continue;}const parent=map.get(c.meta.parentId);if(c.meta.parentId&&(!parent||parent.deleted||parent.type!==c.type)){c.meta.parentId=null;c.meta.issues.push('parent');issues.push('invalidParent');}}
 // Break the lexically smallest edge in each cycle, independent of merge/input ordering.
 for(const start of [...map.keys()].sort()){let cur=map.get(start),path=[],seen=new Map();while(cur?.meta.parentId){if(seen.has(cur.id)){const cycle=path.slice(seen.get(cur.id)).sort(),cut=map.get(cycle[0]);cut.meta.parentId=null;cut.meta.issues.push('cycle');issues.push('invalidCycle');break;}seen.set(cur.id,path.length);path.push(cur.id);cur=map.get(cur.meta.parentId);}}
 for(const c of [...map.values()].sort((a,b)=>a.id.localeCompare(b.id))){let cur=c,depth=1;while(cur.meta.parentId){if(++depth>8){c.meta.parentId=null;c.meta.issues.push('depth');issues.push('invalidDepth');depth=1;break;}cur=map.get(cur.meta.parentId);}c.meta.depth=depth;}
 const children=new Map();for(const c of map.values()){const key=c.meta.parentId||'';if(!children.has(key))children.set(key,[]);children.get(key).push(c);}for(const list of children.values())list.sort((a,b)=>a.meta.order-b.meta.order||a.id.localeCompare(b.id));const items=[];const visit=c=>{items.push(c);for(const child of children.get(c.id)||[])visit(child);};for(const c of children.get('')||[])visit(c);
 return{items,issues:[...new Set(issues)]};
}
function descendants(categoryId,categories=[]){const items=catalog(categories).items,result=[],todo=[categoryId],seen=new Set();while(todo.length){const key=todo.shift();if(seen.has(key))continue;seen.add(key);result.push(key);for(const c of items)if(c.meta.parentId===key&&!c.deleted)todo.push(c.id);}return result;}
const blocked=new Set(['pending','draft','rejected','queued','cancelled','deleted','reversed']);
function confirmed(r){return!!r&&!r.deleted&&!r.pending&&!r._pending&&r.confirmed!==false&&!blocked.has(r.status);}
const fee=r=>r?.entryKind==='fee'||r?._kind==='fee'||r?.synthetic&&!!r.transferId;
const principal=r=>['transfer_in','transfer_out','transfer_marker','transferIn','transferOut'].includes(r?._kind||r?.entryKind||'');
function eligibleRows(rows=[],options={}){if(options.authorized!==true||!['personal','work'].includes(options.section))return[];const C=context(),today=options.today||C.day(),seen=new Set(),out=[];for(const r of rows){if(r?.section!==options.section||!confirmed(r)||principal(r)||!['income','expense'].includes(r.type)||options.type&&r.type!==options.type||options.currency&&r.currency!==options.currency||!C.currencies.includes(r.currency)||!Number.isSafeInteger(r.minor)||r.minor<=0||!C.validDate(r.date))continue;const date=r.date.slice(0,10);if(date>today||options.from&&date<options.from||options.to&&date>options.to)continue;const key=fee(r)&&r.transferId?'fee:'+r.transferId:id(r.id)?'transaction:'+r.id:'';if(!key||seen.has(key))continue;seen.add(key);out.push(r);}return out;}
function percent(value,total){value=BigInt(value);total=BigInt(total);if(total<=0n)return 0;const negative=value<0n,abs=negative?-value:value,scaled=(abs*10000n+total/2n)/total;return(negative?-1:1)*Number(scaled)/100;}
function spending(input={},options={}){if(options.authorized!==true||!['personal','work'].includes(options.section))return{restricted:true,section:options.section,currency:options.currency,rowCount:0,totalMinor:0n,feesMinor:0n,categories:[],issues:[]};const cat=catalog(input.categories||[]),map=new Map(cat.items.map(c=>[c.id,c])),type=options.type||'expense',rows=eligibleRows(input.rows||[],{...options,type}),groups=new Map();let total=0n,fees=0n;for(const r of rows){const key=fee(r)?'__fees__':map.get(r.category)?.type===r.type?r.category:'__uncategorized__';let g=groups.get(key);if(!g){const category=map.get(key),m=category?.meta||meta({icon:key==='__fees__'?'fees':'tag'});g={id:key,categoryId:key,category,meta:m,directMinor:0n,totalMinor:0n,count:0,sharePercent:0};groups.set(key,g);}g.directMinor+=BigInt(r.minor);g.count++;total+=BigInt(r.minor);if(key==='__fees__')fees+=BigInt(r.minor);}
 for(const c of cat.items)if(c.type===type&&!c.deleted&&!groups.has(c.id))groups.set(c.id,{id:c.id,categoryId:c.id,category:c,meta:c.meta,directMinor:0n,totalMinor:0n,count:0,sharePercent:0});for(const g of groups.values()){g.totalMinor=g.directMinor;g.totalCount=g.count;g.sharePercent=percent(g.directMinor,total);}for(const g of groups.values()){let parent=g.meta.parentId,depth=0;while(parent&&depth++<8){const p=groups.get(parent);if(!p)break;p.totalMinor+=g.directMinor;p.totalCount+=g.count;parent=p.meta.parentId;}}
 return{restricted:false,section:options.section,currency:options.currency,rowCount:rows.length,totalMinor:total,feesMinor:fees,categories:[...groups.values()].sort((a,b)=>a.directMinor===b.directMinor?a.id.localeCompare(b.id):a.directMinor>b.directMinor?-1:1),issues:cat.issues};
}
function monthRanges(month,today=context().day()){if(!/^\d{4}-(0[1-9]|1[0-2])$/.test(month)||!context().validDate(today)||today.length!==10)throw Error('v86BudgetInvalid');const[y,m]=month.split('-').map(Number),days=new Date(Date.UTC(y,m,0)).getUTCDate(),pm=m===1?12:m-1,py=m===1?y-1:y,pmonth=String(py).padStart(4,'0')+'-'+String(pm).padStart(2,'0'),pd=new Date(Date.UTC(py,pm,0)).getUTCDate(),from=month+'-01',end=month+'-'+String(days).padStart(2,'0'),elapsed=today<from?0:today>end?days:Number(today.slice(8)),to=elapsed?month+'-'+String(elapsed).padStart(2,'0'):today,pelapsed=Math.min(pd,elapsed),pto=pelapsed?pmonth+'-'+String(pelapsed).padStart(2,'0'):new Date(Date.UTC(py,pm-1,0)).toISOString().slice(0,10);return{range:{month,from,to,elapsedDays:elapsed,daysInMonth:days},previousRange:{month:pmonth,from:pmonth+'-01',to:pto,elapsedDays:pelapsed,daysInMonth:pd}};}
const scope=r=>JSON.stringify([r.section,r.currency,r.categoryId||null,r.period]);
function normalizeBudgets(raw={version:1,items:[]},categories=[],options={}){if(!object(raw)||raw.version!==1||!Array.isArray(raw.items)||raw.items.length>3000)throw Error('v86BudgetInvalid');const C=context(),cats=new Map(categories.map(c=>[c.id,c])),seen=new Set(),scopes=new Set(),items=[];for(const r of raw.items){if(!object(r)||!id(r.id)||seen.has(r.id)||!['personal','work'].includes(r.section)||!C.currencies.includes(r.currency)||!(r.categoryId===null||id(r.categoryId))||!(r.period==='monthly'||/^\d{4}-(0[1-9]|1[0-2])$/.test(r.period))||!Number.isSafeInteger(r.limitMinor)||r.limitMinor<=0||!Number.isInteger(r.warningPercent)||r.warningPercent<50||r.warningPercent>100||r.includeDescendants!==undefined&&typeof r.includeDescendants!=='boolean'||!Number.isSafeInteger(r.rev)||r.rev<1||typeof r.updatedAt!=='string'||!C.validDate(r.updatedAt)||r.deleted!==undefined&&typeof r.deleted!=='boolean')throw Error('v86BudgetInvalid');const cat=cats.get(r.categoryId);if(!r.deleted&&r.categoryId!==null&&r.categoryId!=='__fees__'&&(!cat||cat.type!=='expense'||cat.deleted)&&!options.allowMissingCategories)throw Error('v86BudgetInvalid');seen.add(r.id);const s=scope(r);if(!r.deleted&&scopes.has(s)&&!options.allowDuplicateScopes)throw Error('v86BudgetDuplicate');if(!r.deleted)scopes.add(s);items.push({...r,categoryId:r.categoryId||null,includeDescendants:r.includeDescendants!==false});}return{version:1,items};}
function mergeBudgets(a,b,categories=[]){const left=normalizeBudgets(a||{version:1,items:[]},categories,{allowMissingCategories:true,allowDuplicateScopes:true}),right=normalizeBudgets(b||{version:1,items:[]},categories,{allowMissingCategories:true,allowDuplicateScopes:true}),map=new Map();for(const r of [...left.items,...right.items]){const old=map.get(r.id);if(!old||r.rev>old.rev||r.rev===old.rev&&(r.updatedAt>old.updatedAt||r.updatedAt===old.updatedAt&&canonical(r)>canonical(old)))map.set(r.id,r);}const scopes=new Map();for(const r of map.values()){if(r.deleted)continue;const key=scope(r),old=scopes.get(key);if(!old||r.updatedAt>old.updatedAt||r.updatedAt===old.updatedAt&&(r.rev>old.rev||r.rev===old.rev&&r.id>old.id))scopes.set(key,r);}for(const r of map.values())if(!r.deleted&&scopes.get(scope(r))!==r){r.deleted=true;r.rev=Math.min(Number.MAX_SAFE_INTEGER,r.rev+1);r._planningConflict=true;}return{version:1,items:[...map.values()].sort((a,b)=>a.id.localeCompare(b.id))};}
function effectiveBudgets(raw,options={},categories=[]){const rules=normalizeBudgets(raw||{version:1,items:[]},categories,{allowMissingCategories:true,allowDuplicateScopes:true}).items.filter(r=>!r.deleted&&r.section===options.section&&r.currency===options.currency&&(r.period==='monthly'||r.period===options.month)),map=new Map();for(const r of rules){const key=r.categoryId||'';const old=map.get(key);if(!old||r.period===options.month&&old.period==='monthly'||r.period===old.period&&(r.rev>old.rev||r.rev===old.rev&&r.updatedAt>old.updatedAt))map.set(key,r);}return[...map.values()].sort((a,b)=>String(a.categoryId||'').localeCompare(String(b.categoryId||'')));}
function budgetStatus(rule,spentMinor=0n,previousMinor=0n,count=0){const spent=BigInt(spentMinor),limit=BigInt(rule.limitMinor),remaining=limit-spent,p=percent(spent,limit);return{...rule,spentMinor:spent,previousMinor:BigInt(previousMinor),remainingMinor:remaining,overMinor:remaining<0n?-remaining:0n,percentage:p,progress:Math.min(100,Math.max(0,p)),usedBasisPoints:Math.round(p*100),status:spent>limit?'over':spent===limit?'limit':spent*100n>=limit*BigInt(rule.warningPercent)?'warning':'safe',count,legacy:rule.legacy===true};}
return{create:next=>factory(next),icons:ICONS,colors:COLORS,meta,catalog,validateCategories,descendants,confirmed,eligibleRows,spending,percent,monthRanges,normalizeBudgets,mergeBudgets,effectiveBudgets,budgetStatus,scope};
});
