/* Receipt photo review: optional local OCR, explicit draft confirmation, existing ledger validators. */
(function(root){'use strict';
const A=root.App,O=root.Online,R=root.V14?.Receipts,S=root.V17Scanner,C=root.ReceiptTextCore,G=root.ReceiptOCREngine;
if(!A||!R||!S||!C||!G)return;
const M=root.MasarifiReceiptCamera={},states=new WeakMap(),forms=new WeakMap(),doc=root.document,t=root.tr,esc=root.Core.escape;
V7.addLabels(`
receipt_hint|امسح QR الفاتورة أو اختر صورة الإيصال لقراءة الإجمالي المطبوع محليًا. راجع القيم قبل الحفظ. باركود المنتج وحده لا يحتوي إجمالي الإيصال.|Fatura QR kodunu tarayın veya basılı toplamı cihazda okumak için fiş resmi seçin. Kaydetmeden kontrol edin. Ürün barkodu fiş toplamını içermez.|Scan the invoice QR or choose a receipt image to read its printed total locally. Review before saving. A product barcode alone contains no receipt total.|Scannez le QR ou choisissez l’image du reçu pour lire son total localement. Vérifiez avant d’enregistrer. Un code produit ne contient pas le total.
receipt_image|صورة الإيصال|Fiş resmi|Receipt image|Image du reçu
receipt_camera|تعذّر فتح الكاميرا. اسمح بها أو اختر صورة الإيصال.|Kamera açılamadı. İzin verin veya fiş resmi seçin.|Camera unavailable. Allow access or choose a receipt image.|Caméra indisponible. Autorisez-la ou choisissez une image du reçu.
ocrTitle|قراءة المبلغ المطبوع على الإيصال|Fişte yazılı tutarı oku|Read the printed receipt total|Lire le total imprimé du reçu
ocrPrivacy|تُقرأ الصورة على جهازك ولا تُرفع. عند أول قراءة تُنزّل أدوات القراءة ولغة الإيصال من jsDelivr (عدة MB). يلزم الإنترنت للتنزيل الأول؛ قد تحتاجه مجددًا إذا أُزيلت الملفات المؤقتة.|Görüntü cihazda okunur, yüklenmez. İlk okumada jsDelivr’den motor ve fiş dili indirilir (birkaç MB). İlk indirme ve önbellek temizlenirse tekrar internet gerekir.|The image is read on your device and is not uploaded. First use downloads the reader and receipt language from jsDelivr (several MB). Internet is needed for that download and again if cached files are removed.|L’image est lue sur votre appareil et n’est pas envoyée. La première lecture télécharge le moteur et la langue depuis jsDelivr (plusieurs Mo). Internet est nécessaire au téléchargement et si le cache est effacé.
ocrLanguage|لغة الإيصال|Fiş dili|Receipt language|Langue du reçu
ocrRead|قراءة صورة الإيصال|Fiş resmini oku|Read receipt image|Lire l’image du reçu
ocrCapture|التقاط الإيصال وقراءة المبلغ|Fişi çek ve tutarı oku|Capture receipt to read total|Capturer le reçu pour lire le total
ocrRotate|تدوير 90°|90° döndür|Rotate 90°|Tourner de 90°
ocrCrop|منطقة القراءة|Okuma alanı|Reading area|Zone de lecture
ocrWhole|الإيصال كاملًا|Fişin tamamı|Whole receipt|Reçu entier
ocrLower|النصف السفلي (الإجمالي)|Alt yarı (toplam)|Lower half (total)|Moitié inférieure (total)
ocrCancel|إلغاء القراءة|Okumayı iptal et|Cancel reading|Annuler la lecture
ocrReading|جارٍ التنزيل أو القراءة محليًا…|İndiriliyor veya cihazda okunuyor…|Downloading or reading locally…|Téléchargement ou lecture locale…
ocrReview|مبلغ مقترح؛ راجع جميع الحقول وعدّلها قبل المتابعة.|Önerilen tutar; devam etmeden tüm alanları kontrol edip düzeltin.|Suggested amount. Check and edit every field before continuing.|Montant suggéré. Vérifiez et corrigez tous les champs avant de continuer.
ocrUse|استخدام القيم في مسودة المصروف|Değerleri gider taslağına aktar|Use values in expense draft|Utiliser les valeurs dans le brouillon
ocrConfirm|راجعت المبلغ والعملة والتاريخ والمتجر.|Tutarı, para birimini, tarihi ve mağazayı kontrol ettim.|I checked the amount, currency, date and merchant.|J’ai vérifié le montant, la devise, la date et le commerce.
ocrFinal|اختر الصندوق والتصنيف في القسم الحالي ثم احفظ المصروف. لم يُحفظ شيء بعد.|Geçerli bölümde kasa ve kategori seçip gideri kaydedin. Henüz kayıt yapılmadı.|Choose the cashbox and category in the current section, then save the expense. Nothing has been saved yet.|Choisissez la caisse et la catégorie dans la section actuelle, puis enregistrez. Rien n’est encore enregistré.
ocrManual|نص الإيصال (يمكن لصقه أو تصحيحه)|Fiş metni (yapıştırın veya düzeltin)|Receipt text (paste or correct)|Texte du reçu (coller ou corriger)
ocrParse|استخراج القيم من النص|Metinden değerleri çıkar|Extract values from text|Extraire les valeurs du texte
ocrMissing|لم يظهر إجمالي واضح. قرّب الإيصال أو دوّر الصورة أو صحّح النص وأدخل المبلغ يدويًا.|Net toplam bulunamadı. Yaklaştırın, döndürün veya metni düzeltip tutarı elle girin.|No clear total found. Move closer, rotate the image, correct the text or enter the amount manually.|Aucun total clair. Rapprochez ou tournez l’image, corrigez le texte ou saisissez le montant.
ocrCandidates|مبالغ أخرى محتملة في النص|Metindeki diğer olası tutarlar|Other possible amounts in the text|Autres montants possibles dans le texte
ocrCameraHint|قرّب الإيصال كاملًا وثبّت الهاتف. التصوير لا يحفظ مصروفًا تلقائيًا.|Fişi kadraja alın ve telefonu sabit tutun. Çekim gideri otomatik kaydetmez.|Frame the receipt and hold steady. Capturing never saves an expense automatically.|Cadrez le reçu et stabilisez le téléphone. La capture n’enregistre aucune dépense automatiquement.
receipt_ocr_unavailable|تعذّر تنزيل أداة القراءة. تحقق من الإنترنت أو الصق نص الإيصال؛ لم تُرفع صورتك.|Okuma aracı indirilemedi. İnterneti kontrol edin veya fiş metnini yapıştırın; görüntü yüklenmedi.|Reader download failed. Check the internet or paste receipt text; your image was not uploaded.|Téléchargement du lecteur impossible. Vérifiez Internet ou collez le texte ; l’image n’a pas été envoyée.
receipt_ocr_timeout|استغرقت القراءة وقتًا طويلًا فتوقفت. جرّب صورة أقرب أو النص اليدوي.|Okuma zaman aşımına uğradı. Yakın bir resim veya elle metin deneyin.|Reading took too long and stopped. Try a closer photo or enter text.|La lecture a expiré. Essayez une photo plus proche ou saisissez le texte.
receipt_image_large|الصورة كبيرة جدًا. اختر صورة حتى 8 MB و32 مليون بكسل.|Resim çok büyük. En fazla 8 MB ve32 milyon piksel seçin.|Image too large. Choose up to 8 MB and 32 million pixels.|Image trop grande. Choisissez au maximum 8 Mo et 32 millions de pixels.
receipt_cancelled|أُلغيت القراءة؛ لم يُحفظ شيء.|Okuma iptal edildi; kayıt yapılmadı.|Reading cancelled; nothing saved.|Lecture annulée ; rien n’est enregistré.
`);
const stamp=()=>({section:root.SectionWorkspaces?.scope?.()||A.prefs.section,db:DB.db,box:O.Workspace?.context||(A.page==='online'?O.boxId:'')||'',uid:O.user?.id||null,auth:O.authEpoch,mode:O.modeEpoch,workspace:O.Workspace?.epoch,lock:root.V5?.lockGeneration||0});
const dialog=scope=>scope.tagName==='DIALOG'?scope:scope.closest('dialog');
const current=(scope,proof)=>!!scope?.isConnected&&!!dialog(scope)?.open&&!A.locked&&G.sameContext(proof,stamp());
M.formCurrent=form=>!forms.has(form)||current(form,forms.get(form));
const state=scope=>states.get(scope);
const status=(scope,key)=>{const n=scope.querySelector('[data-ocr-status]');if(n)n.textContent=t(key);};
function stop(scope){const s=state(scope);if(!s)return;s.serial++;s.reader.cancel();s.busy=false;s.job=null;scope.querySelectorAll('[data-ocr-lock]').forEach(n=>n.disabled=false);scope.querySelector('[data-ocr-progress]')?.setAttribute('hidden','');}
function drop(scope){stop(scope);const s=state(scope);if(s){s.source=null;s.candidate=null;s.id=null;}const raw=scope?.querySelector('[data-ocr-text]');if(raw)raw.value='';scope?.querySelector('[data-ocr-photo]')?.replaceChildren();const panel=scope?.querySelector('[data-ocr-review]');if(panel){panel.hidden=true;panel.replaceChildren();}scope?.querySelector('[data-ocr-tools]')?.setAttribute('hidden','');}
function mount(scope,holder){if(!scope||!holder||states.has(scope))return;const proof=stamp(),s={proof,serial:0,busy:false,source:null,rotation:0,candidate:null,id:null,reader:G.createReader({load:()=>G.load(root)})};states.set(scope,s);if(scope.tagName==='FORM')forms.set(scope,proof);
const element=doc.createElement('section');element.className='receipt-ocr';element.dataset.ocrWorkspace='';element.innerHTML=`<h3>${esc(t('ocrTitle'))}</h3><p class="hint">${esc(t('ocrPrivacy'))}</p><p class="hint">${esc(t('ocrCameraHint'))}</p><label>${esc(t('ocrLanguage'))}<select data-ocr-language data-ocr-lock>${[['ar','العربية'],['tr','Türkçe'],['en','English'],['fr','Français']].map(([v,n])=>`<option value="${v}"${v===A.prefs.language?' selected':''}>${n}</option>`).join('')}</select></label><div data-ocr-photo class="receipt-ocr-photo"></div><div data-ocr-tools hidden><div class="row"><button type="button" data-ocr="rotate" data-ocr-lock>${esc(t('ocrRotate'))}</button><label>${esc(t('ocrCrop'))}<select data-ocr-crop data-ocr-lock><option value="whole">${esc(t('ocrWhole'))}</option><option value="lower">${esc(t('ocrLower'))}</option></select></label></div><button type="button" data-ocr="read" data-ocr-lock class="primary">${esc(t('ocrRead'))}</button></div><div data-ocr-progress hidden><progress max="100" value="0" aria-label="${esc(t('ocrReading'))}"></progress><button type="button" data-ocr="cancel">${esc(t('ocrCancel'))}</button></div><p data-ocr-status role="status" aria-live="polite"></p><details><summary>${esc(t('ocrManual'))}</summary><textarea data-ocr-text rows="4" maxlength="16384" dir="auto" aria-label="${esc(t('ocrManual'))}"></textarea><button type="button" data-ocr="parse" data-ocr-lock>${esc(t('ocrParse'))}</button></details><section data-ocr-review hidden></section>`;holder.append(element);
const camera=scope.querySelector(scope.tagName==='DIALOG'?'[data-scan-camera]':'[data-receipt-camera]');if(camera&&!camera.querySelector('[data-ocr="capture"]'))camera.insertAdjacentHTML('beforeend',`<button type="button" data-ocr="capture">${esc(t('ocrCapture'))}</button>`);
dialog(scope).addEventListener('close',()=>drop(scope),{once:true});
}
function rotated(s,crop='whole'){const source=s.source,out=doc.createElement('canvas'),right=s.rotation%180!==0;out.width=right?source.height:source.width;out.height=right?source.width:source.height;const ctx=out.getContext('2d');ctx.translate(out.width/2,out.height/2);ctx.rotate(s.rotation*Math.PI/180);ctx.drawImage(source,-source.width/2,-source.height/2);if(crop==='lower'){const half=doc.createElement('canvas');half.width=out.width;half.height=Math.ceil(out.height/2);half.getContext('2d').drawImage(out,0,Math.floor(out.height/2),out.width,half.height,0,0,half.width,half.height);return half;}return out;}
function paint(scope){const s=state(scope),canvas=rotated(s,scope.querySelector('[data-ocr-crop]').value);canvas.setAttribute('role','img');canvas.setAttribute('aria-label',t('mediaImageSource'));scope.querySelector('[data-ocr-photo]').replaceChildren(canvas);scope.querySelector('[data-ocr-tools]').hidden=false;}
function putImage(scope,source){const s=state(scope),size=G.dimensions(source.naturalWidth||source.videoWidth||source.width,source.naturalHeight||source.videoHeight||source.height),canvas=doc.createElement('canvas');canvas.width=size.width;canvas.height=size.height;canvas.getContext('2d').drawImage(source,0,0,size.width,size.height);s.source=canvas;s.rotation=0;s.candidate=null;s.id=null;scope.querySelector('[data-ocr-text]').value='';scope.querySelector('[data-ocr-review]').hidden=true;paint(scope);status(scope,'ocrCameraHint');}
M.image=async(scope,file)=>{const s=state(scope);if(!s||!file||!current(scope,s.proof))return;if(file.size>8000000)throw Error('receipt_image_large');if(!['image/jpeg','image/png','image/webp'].includes(file.type))throw Error('v17ScanImageHint');stop(scope);S.cancel();R.sequence++;R.stop();const serial=s.serial,url=URL.createObjectURL(file);try{const image=new Image();await new Promise((resolve,reject)=>{image.onload=resolve;image.onerror=()=>reject(Error('receipt_invalid'));image.src=url;});if(!current(scope,s.proof)||serial!==s.serial)return;putImage(scope,image);const decoded=await S.decode(s.source);if(!current(scope,s.proof)||serial!==s.serial)return;if(decoded?.format==='qr_code'){if(scope.tagName==='DIALOG')await S.receive(decoded.raw,decoded.format);else try{await R.review(scope,decoded.raw);}catch{status(scope,'ocrMissing');}}else if(decoded)status(scope,'v17ScanBarcodeHint');}finally{URL.revokeObjectURL(url);}};
async function duplicate(id){G.validateId(id);if(await DB.get('meta','v14Receipt:scan:'+id.slice(5)))return true;if(await DB.get('transactions',id))return true;if((A.trash||[]).some(x=>x.store==='transactions'&&x.record?.id===id))return true;return [...O.snapshots.values()].some(s=>s.entries?.some(e=>e.record_id===id))||O.pending.some(p=>p.userId===O.user?.id&&p.recordId===id&&['pending','approved'].includes(p.status));}
M.duplicate=duplicate;
async function review(scope,text){const s=state(scope),serial=++s.serial;if(!current(scope,s.proof))return;const language=scope.querySelector('[data-ocr-language]').value,defaultCurrency=scope.tagName==='FORM'?(A.account?.(scope.querySelector('#txAccount')?.value)?.currency||scope.elements.namedItem('currency')?.value):(O.snapshots.get(s.proof.box)?.box.currency||A.account?.(A.filter?.accountId)?.currency||A.prefs[A.prefs.section==='work'?'currencyWork':'currencyPersonal']);const candidate=C.parse(text,{language,currency:defaultCurrency||'TRY',minor:Core.minor});const id=await G.fingerprint(candidate.text,root.crypto);if(!current(scope,s.proof)||serial!==s.serial)return;if(await duplicate(id))throw Error('receipt_duplicate');if(!current(scope,s.proof)||serial!==s.serial)return;s.candidate=candidate;s.id=id;scope.querySelector('[data-ocr-text]').value=candidate.text;const panel=scope.querySelector('[data-ocr-review]');panel.hidden=false;panel.innerHTML=`<p class="notice">${esc(t('ocrReview'))}</p>${!candidate.minor?`<p class="hint">${esc(t('ocrMissing'))}</p>`:''}<div class="fields"><label>${esc(t('amount'))}<input data-ocr-amount value="${esc(candidate.amount||'')}" inputmode="decimal" dir="ltr"></label><label>${esc(t('currency'))}<select data-ocr-currency>${Core.currencies.filter(c=>!['XAU','XAG'].includes(c)).map(c=>`<option${c===candidate.currency?' selected':''}>${esc(c)}</option>`).join('')}</select></label><label>${esc(t('date'))}<input data-ocr-date type="date" value="${esc(candidate.date||'')}"></label><label>${esc(t('receipt_merchant'))}<input data-ocr-merchant value="${esc(candidate.merchant||'')}" maxlength="160"></label></div>${candidate.candidates.length>1?`<details><summary>${esc(t('ocrCandidates'))}</summary>${candidate.candidates.map(c=>`<p><bdi>${esc(c.amount+' '+c.currency)}</bdi> · ${esc(c.line)}</p>`).join('')}</details>`:''}<p class="hint">${esc(t('ocrFinal'))}</p><label class="check"><input data-ocr-confirm type="checkbox">${esc(t('ocrConfirm'))}</label><button type="button" data-ocr="apply" class="primary">${esc(t('ocrUse'))}</button>`;status(scope,'');}
M.review=review;
async function read(scope){const s=state(scope);if(!s?.source||s.busy||!current(scope,s.proof))return;stop(scope);const serial=s.serial,job={};s.job=job;s.busy=true;scope.querySelectorAll('[data-ocr-lock]').forEach(n=>n.disabled=true);scope.querySelector('[data-ocr-progress]').hidden=false;status(scope,'ocrReading');try{const image=rotated(s,scope.querySelector('[data-ocr-crop]').value),result=await s.reader.read(image,scope.querySelector('[data-ocr-language]').value,{isCurrent:()=>current(scope,s.proof)&&s.serial===serial,onProgress:value=>{scope.querySelector('progress').value=value;}});if(!current(scope,s.proof)||s.serial!==serial)return;try{await review(scope,result.text);}catch(e){if(current(scope,s.proof)&&s.job===job)status(scope,e.message==='receipt_invalid'?'ocrMissing':e.message);}}catch(e){if(current(scope,s.proof)&&s.serial===serial)status(scope,e.message==='receipt_cancelled'?e.message:e.message==='receipt_ocr_timeout'?e.message:'receipt_ocr_unavailable');}finally{if(current(scope,s.proof)&&s.job===job){s.job=null;s.busy=false;scope.querySelectorAll('[data-ocr-lock]').forEach(n=>n.disabled=false);scope.querySelector('[data-ocr-progress]').hidden=true;}}}
async function apply(scope){const s=state(scope);if(!s?.candidate||s.busy||!current(scope,s.proof))return;const proof=s.proof,serial=s.serial,scanId=s.id;const q=name=>scope.querySelector('[data-ocr-'+name+']'),currency=q('currency').value,amount=Core.minor(q('amount').value,currency,A.prefs.language),date=q('date').value,merchant=q('merchant').value.trim();if(!q('confirm').checked||!merchant)throw Error('required');if(!/^20\d\d-\d\d-\d\d$/.test(date)||!Core.validDate(date+'T12:00'))throw Error('invalidDate');s.busy=true;try{if(await duplicate(scanId))throw Error('receipt_duplicate');if(!current(scope,proof)||s.serial!==serial)return;const snap=proof.box?O.snapshots.get(proof.box):null;if(snap&&(!O.familyCan('add_expense',null,snap)||snap.box.currency!==currency&&(O.familyPermissions?.(snap)?.role||snap.limits?.role)!=='owner'))throw Error('receipt_currency');if(!s.proof.box&&!A.accounts.some(a=>a.currency===currency))throw Error('receipt_currency');let form=scope;if(scope.tagName==='DIALOG'){const target=S.allowed(),id=scanId;S.close();if(!G.sameContext(proof,stamp())||A.locked)return;if(target.box){O.boxId=target.box;O.entryForm('',false,{kind:'expense'});}else A.transactionForm('expense');form=doc.querySelector('#dialog[open] form');if(!form||!M.formCurrent(form))return;form.receiptScanId=id;}else{if(!M.formCurrent(form))return;form.receiptScanId=scanId;}
const account=form.querySelector('#txAccount'),currencyInput=form.elements.namedItem('currency');if(account){const selected=A.account(account.value);if(selected?.currency!==currency){const match=A.accounts.find(a=>a.currency===currency);if(!match)throw Error('receipt_currency');account.value=match.id;account.dispatchEvent(new Event('change',{bubbles:true}));}}else if(currencyInput){if(currencyInput.tagName!=='SELECT'&&currencyInput.value!==currency)throw Error('receipt_currency');if(currencyInput.tagName==='SELECT'&&![...currencyInput.options].some(x=>x.value===currency))throw Error('receipt_currency');currencyInput.value=currency;currencyInput.dispatchEvent(new Event('change',{bubbles:true}));const snap=O.snapshots.get(form.dataset.receiptBox),fx=form.elements.namedItem('fx');if(snap?.box.currency!==currency&&fx)fx.value='';}
const kind=form.elements.namedItem('type')||form.elements.namedItem('kind');if(kind&&kind.value!=='expense'){kind.value='expense';kind.dispatchEvent(new Event('change',{bubbles:true}));}form.receipt=null;form.receiptCandidate=null;form.receiptRemember=false;const qrPreview=form.querySelector('[data-receipt-preview]');if(qrPreview)qrPreview.hidden=true;form.familyRecordId=form.receiptScanId;form.elements.namedItem('amount').value=Core.fixedMinor(amount,Core.digits(currency));form.elements.namedItem('date').value=date+'T12:00';const party=form.elements.namedItem('party');if(party)party.value=merchant;const description=form.elements.namedItem('description');if(description&&!description.value.trim())description.value=merchant;const category=form.elements.namedItem('category');if(category){category.required=true;if(!category.value)category.focus();}form.dispatchEvent(new Event('input',{bubbles:true}));if(form===scope){q('confirm').checked=false;status(scope,'ocrFinal');}else A.toast(t('ocrFinal'));}finally{if(s.serial===serial)s.busy=false;}}
const attach=R.attach;R.attach=function(form,...args){if(form)forms.set(form,stamp());const result=attach.call(this,form,...args);if(!args[0])mount(form,form?.querySelector('[data-receipt-root]'));return result;};
const originalReview=R.review;R.review=async function(form,raw){if(typeof raw==='string'&&raw.trim()&&!raw.trim().startsWith('{')){if(!states.has(form))mount(form,form.querySelector('[data-receipt-root]'));return review(form,raw);}return originalReview.apply(this,arguments);};
const originalApply=R.apply;R.apply=function(form){if(!M.formCurrent(form))throw Error('v17ScanChanged');const result=originalApply.apply(this,arguments);if(form.receipt){delete form.receiptScanId;if(/^scan-[a-f0-9]{64}$/.test(form.familyRecordId||''))delete form.familyRecordId;}return result;};
R.image=(form,file)=>M.image(form,file);
const open=S.open;S.open=function(){const previous=S.session;const result=open.apply(this,arguments);if(S.session){if(S.session!==previous){drop(S.session.dialog);states.delete(S.session.dialog);}if(!S.session.ocrProof)S.session.ocrProof=stamp();mount(S.session.dialog,S.session.dialog.querySelector('[data-scan-inputs]'));}return result;};
const scannerCurrent=S.current;S.current=function(session){return scannerCurrent.call(this,session)&&(!session.ocrProof||G.sameContext(session.ocrProof,stamp()));};
S.image=file=>M.image(S.session?.dialog,file).catch(e=>{if(S.session)S.error(e);});
const present=S.present;S.present=function(){if(S.session)drop(S.session.dialog);return present.apply(this,arguments);};
const close=S.close;S.close=function(){if(S.session)drop(S.session.dialog);return close.apply(this,arguments);};
const commit=DB.commit;DB.commit=async function(ops){const proof=stamp(),extra=[];for(const op of ops){const row=op.store==='transactions'?op.value:op.store==='trash'&&op.value?.store==='transactions'?op.value.record:null;if(!row||!/^scan-[a-f0-9]{64}$/.test(row.id))continue;const id='v14Receipt:scan:'+row.id.slice(5);if(!ops.some(o=>o.store==='meta'&&o.value?.id===id)&&!extra.some(o=>o.value.id===id)){const old=await DB.get('meta',id);if(!G.sameContext(proof,stamp())||A.locked)throw Error('v17ScanChanged');if(old&&old.value!==row.id)throw Error('receipt_duplicate');if(!old)extra.push({store:'meta',value:{id,value:row.id,rev:1},expected:0});}}return commit.call(this,[...ops,...extra]);};
doc.addEventListener('click',async event=>{const b=event.target.closest('[data-ocr]');if(!b)return;const scope=b.closest('form')||b.closest('dialog'),s=state(scope);if(!s||!current(scope,s.proof))return;event.preventDefault();event.stopImmediatePropagation();try{const action=b.dataset.ocr;if(action==='cancel'){stop(scope);status(scope,'receipt_cancelled');}else if(s.busy)return;else if(action==='capture'){const video=scope.querySelector('video');if(!video?.videoWidth)throw Error('receipt_camera');putImage(scope,video);S.cancel();R.sequence++;R.stop();}else if(action==='rotate'&&s.source){s.rotation=(s.rotation+90)%360;paint(scope);}else if(action==='read')await read(scope);else if(action==='parse')await review(scope,scope.querySelector('[data-ocr-text]').value);else if(action==='apply')await apply(scope);}catch(e){if(current(scope,s.proof))status(scope,e.message);}},true);
doc.addEventListener('change',event=>{const form=event.target.closest('form');if(event.target.name==='boxId'&&form&&forms.has(form)&&!form.dataset.receiptRecord){const old=forms.get(form),next=stamp(),same=G.sameContext({...old,box:next.box,workspace:next.workspace},next);if(same&&form.dataset.receiptBox===event.target.value&&O.boxId===event.target.value&&form.dataset.familyIdentity===O.user?.id){R.sequence++;R.stop();drop(form);forms.set(form,next);if(state(form))state(form).proof=next;delete form.receiptScanId;}}if(event.target.matches('[data-ocr-crop]')){const scope=event.target.closest('form')||event.target.closest('dialog');if(state(scope)?.source)paint(scope);}});
const cancelAll=()=>{for(const scope of doc.querySelectorAll('form, #v17Scanner'))if(states.has(scope))drop(scope);};
root.addEventListener('v6:locked',cancelAll);root.addEventListener('pagehide',cancelAll);doc.addEventListener('masarifi:navigation',cancelAll);doc.addEventListener('visibilitychange',()=>{if(doc.hidden)cancelAll();});
})(window);
