/* Full subscription route. Public server plans and existing approval workflows remain authoritative. */
(function(root){'use strict';
const A=root.App,O=root.Online,S=O?.Service,V6=root.V6,V7=root.V7,doc=root.document;
if(!A||!O||!S||!V6||!V7||root.MasarifiSubscription)return;
const languages=['ar','tr','en','fr'],words={
 browserOnline:['المتصفح يبلغ عن اتصال بالشبكة','Tarayıcı çevrimiçi bildiriyor','Browser reports online','Le navigateur indique être en ligne'],
 browserOffline:['المتصفح يبلغ عن عدم الاتصال','Tarayıcı çevrimdışı bildiriyor','Browser reports offline','Le navigateur indique être hors ligne'],
 expired:['انتهى الاشتراك؛ اختر باقة للتجديد','Abonelik sona erdi; yenilemek için paket seçin','Subscription expired; choose a plan to renew','Abonnement expiré ; choisissez une offre pour renouveler'],
 renew:['تجديد الاشتراك','Aboneliği yenile','Renew subscription','Renouveler l’abonnement'],
 cachedStatus:['آخر حالة مؤكدة؛ اتصل لتحديثها','Son doğrulanan durum; yenilemek için bağlanın','Last verified status; connect to refresh','Dernier état vérifié ; connectez-vous pour actualiser'],
 browseHint:['اسحب أفقيًا لمقارنة الباقات','Paketleri karşılaştırmak için yatay kaydırın','Scroll horizontally to compare plans','Faites défiler horizontalement pour comparer les offres'],
 current:['الباقة الحالية','Geçerli paket','Current plan','Offre actuelle'],localPlan:['استخدام محلي مجاني','Ücretsiz yerel kullanım','Free local use','Utilisation locale gratuite'],unverified:['حالة الاشتراك غير مؤكدة؛ اتصل لتحديثها','Abonelik doğrulanmadı; yenilemek için bağlanın','Subscription status unverified; connect to refresh','Abonnement non vérifié ; connectez-vous pour actualiser'],connection:['حالة الاتصال','Bağlantı durumu','Connection','Connexion'],onlineNow:['متصل بالإنترنت','Çevrimiçi','Online','En ligne'],offlineNow:['دون إنترنت','Çevrimdışı','Offline','Hors ligne'],localNow:['الوضع المحلي','Yerel mod','Local mode','Mode local'],
 title:['الاشتراك','Abonelik','Subscription','Abonnement'],
 eyebrow:['مساحة مشتركة، بخطوة واضحة','Ortak alan, açık bir adım','A shared space, a clear next step','Un espace partagé, une étape claire'],
 intro:['اختر المدة التي تناسبك، ثم تابع طلبك مع الإدارة من داخل التطبيق.','Size uygun süreyi seçin, ardından talebinizi uygulama içinden yönetimle takip edin.','Choose the duration that suits you, then follow your request with support inside the app.','Choisissez la durée qui vous convient, puis suivez votre demande avec l’équipe dans l’application.'],
 choose:['اختر باقتك','Paketinizi seçin','Choose your plan','Choisissez votre offre'],
 total:['السعر الإجمالي','Toplam fiyat','Total price','Prix total'],
 days:['{n} يومًا','{n} gün','{n} days','{n} jours'],
 unlimited:['مدة مفتوحة','Süresiz','Open duration','Durée ouverte'],
 other:['باقات إضافية','Diğer paketler','More plans','Autres offres'],
 selected:['الباقة المختارة','Seçilen paket','Selected plan','Offre choisie'],
 select:['اختيار الباقة','Paketi seç','Select plan','Choisir cette offre'],
 empty:['لا توجد باقات متاحة الآن. يمكنك التواصل مع الإدارة.','Şu anda paket yok. Yönetimle iletişim kurabilirsiniz.','No plans are available right now. You can contact support.','Aucune offre n’est disponible actuellement. Vous pouvez contacter l’équipe.'],
 preparing:['جارٍ تحديث الباقات وحالة الاشتراك…','Paketler ve abonelik durumu yenileniyor…','Refreshing plans and subscription status…','Actualisation des offres et de l’abonnement…'],
 local:['يمكنك استعراض آخر الباقات المحفوظة. فعّل أونلاين لتحديث الأسعار وإرسال الطلب.','Son kayıtlı paketleri görebilirsiniz. Fiyatları yenilemek ve talep göndermek için çevrimiçi modu açın.','You can browse the last saved plans. Enable online mode to refresh prices and send a request.','Consultez les dernières offres enregistrées. Activez le mode en ligne pour actualiser les prix et envoyer une demande.'],
 offline:['أعد الاتصال لتحديث الأسعار وإرسال الطلب. بياناتك الشخصية متاحة دون إنترنت.','Fiyatları yenilemek ve talep göndermek için yeniden bağlanın. Kişisel verileriniz çevrimdışı kullanılabilir.','Reconnect to refresh prices and send a request. Your personal data remains available offline.','Reconnectez-vous pour actualiser les prix et envoyer une demande. Vos données personnelles restent accessibles hors ligne.'],
 stale:['هذه آخر أسعار محفوظة؛ سنراجع السعر الحالي قبل إرسال الطلب.','Bunlar son kayıtlı fiyatlardır; göndermeden önce güncel fiyatı kontrol edeceğiz.','These are the last saved prices; we will check the current price before submitting.','Voici les derniers prix enregistrés ; le prix actuel sera vérifié avant l’envoi.'],
 connect:['تفعيل أونلاين وتحديث الباقات','Çevrimiçi modu aç ve paketleri yenile','Enable online mode and refresh plans','Activer le mode en ligne et actualiser'],
 refresh:['تحديث الباقات والحالة','Paketleri ve durumu yenile','Refresh plans and status','Actualiser les offres et le suivi'],
 error:['تعذر تحديث الباقات الآن. حاول مجددًا عند استقرار الاتصال.','Paketler şu anda yenilenemedi. Bağlantı düzeldiğinde yeniden deneyin.','Plans could not be refreshed. Try again when your connection is stable.','Impossible d’actualiser les offres. Réessayez avec une connexion stable.'],
 checkout:['تفاصيل طلب التفعيل','Etkinleştirme talebi ayrıntıları','Activation request details','Détails de la demande d’activation'],
 payment:['تعليمات الدفع','Ödeme talimatları','Payment instructions','Instructions de paiement'],
 instructionsMissing:['تواصل مع الإدارة لمعرفة طريقة الدفع قبل إرسال طلبك.','Talebinizi göndermeden önce ödeme yöntemi için yönetimle iletişim kurun.','Contact support for payment instructions before sending your request.','Contactez l’équipe pour connaître les modalités de paiement avant d’envoyer votre demande.'],
 reference:['مرجع الدفع','Ödeme referansı','Payment reference','Référence du paiement'],
 optional:['اختياري','İsteğe bağlı','Optional','Facultatif'],
 referenceHint:['يمكنك إضافة مرجع التحويل الآن، وإرسال صورة أو PDF في محادثة الطلب بعد إنشائه.','Havale referansını şimdi ekleyebilir, talep oluşturulduktan sonra görüşmeye görsel veya PDF gönderebilirsiniz.','Add a transfer reference now; attach an image or PDF in the request conversation after creating it.','Ajoutez une référence de virement ; joignez une image ou un PDF dans la conversation après la création de la demande.'],
 review:['يبدأ الاشتراك بعد مراجعة الإدارة وتأكيد استلام الدفع.','Abonelik, yönetim incelemesi ve ödemenin alındığının onaylanmasıyla başlar.','Your subscription starts after support reviews and confirms receipt of payment.','L’abonnement commence après vérification et confirmation du paiement par l’équipe.'],
 submit:['إرسال طلب التفعيل','Etkinleştirme talebi gönder','Send activation request','Envoyer la demande d’activation'],
 sending:['جارٍ إرسال الطلب…','Talep gönderiliyor…','Sending request…','Envoi de la demande…'],
 changed:['تغيّرت تفاصيل الباقة. راجع السعر والمدة الحاليين، ثم أرسل طلبك.','Paket ayrıntıları değişti. Güncel fiyatı ve süreyi kontrol edip yeniden gönderin.','This plan changed. Review the current price and duration, then submit your request.','Cette offre a changé. Vérifiez le prix et la durée actuels, puis envoyez votre demande.'],
 removed:['هذه الباقة لم تعد متاحة. اختر باقة أخرى أو تواصل مع الإدارة.','Bu paket artık mevcut değil. Başka bir paket seçin veya yönetimle iletişim kurun.','This plan is no longer available. Choose another plan or contact support.','Cette offre n’est plus disponible. Choisissez une autre offre ou contactez l’équipe.'],
 requestQuote:['سعر طلبك المحفوظ','Talebinizin kayıtlı fiyatı','Your saved request quote','Prix enregistré de votre demande'],
 existingRequest:['هذا طلبك الحالي؛ يحتفظ بسعره الأصلي. افتح المحادثة لمتابعته.','Bu mevcut talebinizdir; ilk fiyatı korunur. Takip etmek için görüşmeyi açın.','This is your existing request; its original quote is preserved. Open the conversation to follow it.','Il s’agit de votre demande existante ; son prix initial est conservé. Ouvrez la conversation pour la suivre.'],
 requestSaved:['تم إرسال طلبك. افتح محادثته لإرفاق إثبات الدفع ومتابعة الرد.','Talebiniz gönderildi. Ödeme belgesi eklemek ve yanıtı takip etmek için görüşmesini açın.','Your request was sent. Open its conversation to attach payment evidence and follow replies.','Votre demande a été envoyée. Ouvrez la conversation pour joindre un justificatif et suivre les réponses.'],
 openRequest:['فتح محادثة الطلب','Talep görüşmesini aç','Open request conversation','Ouvrir la conversation'],
 ambiguous:['تعذر التحقق من نتيجة الإرسال. حدّث الحالة قبل المحاولة مجددًا لتجنب تكرار الطلب.','Gönderim sonucu doğrulanamadı. Yinelenen talep oluşmaması için tekrar denemeden önce durumu yenileyin.','The submission result could not be verified. Refresh status before trying again to avoid a duplicate request.','Le résultat de l’envoi n’a pas pu être vérifié. Actualisez le suivi avant de réessayer pour éviter un doublon.'],
 active:['اشتراكك فعال','Aboneliğiniz etkin','Your subscription is active','Votre abonnement est actif'],
 expires:['ينتهي في','Bitiş','Ends on','Expire le'],
 pending:['بانتظار مراجعة الدفع','Ödeme incelemesi bekleniyor','Payment review pending','Paiement en cours de vérification'],
 contact:['تواصل مع الإدارة','Yönetimle iletişim','Contact support','Contacter l’équipe'],
 messages:['الرسائل والفواتير','Mesajlar ve faturalar','Messages and invoices','Messages et factures'],
 steps:['من الاختيار إلى التفعيل','Seçimden etkinleştirmeye','From choice to activation','Du choix à l’activation'],
 step1:['اختر المدة','Süreyi seçin','Choose a duration','Choisissez la durée'],
 step2:['راجع تعليمات الدفع','Ödeme talimatlarını inceleyin','Review payment instructions','Consultez les instructions de paiement'],
 step3:['أرسل الطلب وتابع الرد','Talebi gönderip yanıtı takip edin','Send your request and follow replies','Envoyez la demande et suivez les réponses'],
 free:['استخدامك المحلي يبقى مجانيًا. المشاركة والرسائل والمزامنة تحتاج إلى الإنترنت والصلاحيات المناسبة.','Yerel kullanım ücretsizdir. Paylaşım, mesajlaşma ve eşitleme için internet ve uygun yetkiler gerekir.','Local use stays free. Sharing, messages and sync need internet and the appropriate permissions.','L’utilisation locale reste gratuite. Partage, messages et synchronisation nécessitent Internet et les autorisations adaptées.'],
 pick:['اختر باقة للمتابعة','Devam etmek için paket seçin','Choose a plan to continue','Choisissez une offre pour continuer']
};
const t=(key,vars={})=>{let value=words[key]?.[languages.indexOf(A.prefs.language)]||words[key]?.[2]||key;for(const [k,v] of Object.entries(vars))value=value.replaceAll('{'+k+'}',String(v));return value;},esc=value=>root.Core.escape(String(value??'')),loc=value=>typeof value==='string'?value:value?.[A.prefs.language]||value?.en||value?.ar||'',guest=()=>!!O.Workspace?.guest();
const stamp=()=>({uid:O.user?.id||'',auth:O.authEpoch||0,mode:O.modeEpoch||0,lock:root.V5?.lockGeneration||0}),same=(a,b)=>!!a&&a.uid===b.uid&&a.auth===b.auth&&a.mode===b.mode&&a.lock===b.lock;
const valid=p=>p&&typeof p.id==='string'&&p.active!==false&&Number.isSafeInteger(Number(p.price_minor))&&Number(p.price_minor)>=0&&/^[A-Z0-9]{3,8}$/.test(String(p.currency||''));
const duration=p=>Number.isFinite(Number(p.duration_days))&&Number(p.duration_days)>0?t('days',{n:Number(p.duration_days)}):t('unlimited');
const price=(minor,currency)=>{try{return A.money(Number(minor),currency);}catch{return String(currency)+' '+String(Number(minor)/10**(root.Core.digits?.(currency)??2));}};
const quote=r=>{const minor=r?.quoted_price_minor??r?.price_minor,currency=r?.quoted_currency||r?.currency;return minor!=null&&Number.isSafeInteger(Number(minor))&&Number(minor)>=0&&/^[A-Z0-9]{3,8}$/.test(String(currency||''))?price(minor,currency):'';};
const signature=p=>p?JSON.stringify([p.id,p.active,Number(p.price_minor),p.currency,p.duration_days,loc(p.labels)]):'';
const action=(kind,label,extra='',cls='')=>`<button type="button" data-v85-subscription="${kind}" class="${cls}" ${extra}>${esc(label)}</button>`;
const ascii=value=>String(value??'').replace(/[\u0660-\u0669\u06f0-\u06f9]/g,d=>String(d.charCodeAt(0)-(d>='\u06f0'?0x6f0:0x660)));
const P=root.MasarifiSubscription={phase:'idle',seq:0,job:null,verified:null,scope:null,reference:'',referencePlan:'',sending:false,request:null,ambiguous:false,note:'',error:'',
 licenseState(){const identity=!!O.user&&!O.user.localOnly&&!!O.sessionReady,verified=identity&&Number.isInteger(O.authEpoch)&&O.licenseValidatedEpoch===O.authEpoch,sub=verified?O.license?.subscription:null,end=sub?.ends_at,expired=!!sub&&end!=='infinity'&&Number.isFinite(Date.parse(end))&&Date.parse(end)<=Date.now(),pending=verified?this.pendingForUser():[],active=verified&&O.license?.active===true&&!expired;return{verified,sub,pending,active,expired,kind:active?'active':pending.length?'pending':expired?'expired':verified||!O.user||O.user.localOnly?'local':'unverified',cached:verified&&!this.connected()};},
 pendingForUser(requests=O.requests,uid=O.user?.id){return uid?(requests||[]).filter(r=>r.id&&r.status==='pending_review'&&(!(r.requester_user_id||r.user_id)||(r.requester_user_id||r.user_id)===uid)):[];},
 pendingRequests(){return this.licenseState().pending;},
 plans(){return(O.plans||[]).filter(valid);},selected(){return this.plans().find(p=>p.id===V7.routeState?.subscriptionPlan)||null;},
 current(proof,seq=this.seq){return!A.locked&&!guest()&&A.page==='subscription'&&seq===this.seq&&same(proof,stamp());},
 connected(){return navigator.onLine!==false&&!O.networkPaused&&O.sessionReady&&O.user&&!O.user.localOnly;},
 verifiedNow(){return this.phase==='ready'&&this.connected()&&this.licenseState().verified&&same(this.verified,stamp());},
 capture(){const form=doc.getElementById('v85SubscriptionRequest');if(form&&same(this.scope,stamp())){this.reference=String(form.elements.reference?.value||'').slice(0,300);this.referencePlan=form.dataset.plan||'';}},
 invalidate(){this.seq++;this.job=null;this.verified=null;this.scope=null;this.reference='';this.referencePlan='';this.request=null;this.ambiguous=false;this.sending=false;this.connecting=null;this.note='';this.error='';this.phase='idle';},
 syncScope(){const proof=stamp();if(!same(this.scope,proof)){if(this.connecting){this.scope=proof;this.verified=null;this.reference='';this.referencePlan='';this.request=null;this.ambiguous=false;}else{this.invalidate();this.scope=proof;}}},
 async open(id=''){if(A.locked||guest())return;const state=id?{subscriptionPlan:String(id)}:{};await V7.navigate('subscription',state);if(A.page!=='subscription')return;return this.job?.promise;},
 async choose(id){if(A.locked||guest()||!this.plans().some(p=>p.id===id))return;await V7.navigate('subscription',{subscriptionPlan:id});if(A.page!=='subscription'||V7.routeState?.subscriptionPlan!==id)return;this.mount();doc.getElementById('v85SubscriptionRequest')?.scrollIntoView?.({block:'nearest',behavior:root.matchMedia?.('(prefers-reduced-motion: reduce)')?.matches?'auto':'smooth'});},
 async load(connect=false){
  if(A.locked||guest()||A.page!=='subscription'||this.sending)return;if(this.job?.current()||this.job&&this.connecting===this.job)return this.job.promise;
  this.capture();this.syncScope();const seq=++this.seq,initial=stamp(),lock=initial.lock,uid=initial.uid;let proof=initial;
  const current=()=>!A.locked&&!guest()&&A.page==='subscription'&&seq===this.seq&&lock===(root.V5?.lockGeneration||0)&&same(proof,stamp());
  const job={current};this.job=job;if(connect)this.connecting=job;this.phase='loading';this.verified=null;this.error='';this.repaint();
  job.promise=(async()=>{try{
   if(connect){await S.ensure();if(A.locked||guest()||A.page!=='subscription'||seq!==this.seq||lock!==(root.V5?.lockGeneration||0)||(uid&&uid!==O.user?.id))return;if(!O.sessionReady&&!O.networkPaused&&navigator.onLine!==false){await O.enableOnline();if(A.locked||guest()||A.page!=='subscription'||seq!==this.seq||lock!==(root.V5?.lockGeneration||0)||(uid&&uid!==O.user?.id))return;}proof=stamp();this.scope=proof;}
   if(!current())return;if(!this.connected()){this.phase=navigator.onLine===false?'offline':'local';return;}
   const session=await O.requestSession();if(!current())return;await O.fetchPublic();if(!current())return;await O.checkSession(session);if(!current())return;
   await O.refreshLicense();if(!current())return;this.verified=proof;this.phase='ready';this.ambiguous=false;this.error='';
   if(this.request&&!(O.requests||[]).some(r=>r.id===this.request.id))this.request=null;
  }catch(error){if(connect&&this.job===job&&seq===this.seq&&!A.locked&&A.page==='subscription'&&lock===(root.V5?.lockGeneration||0)&&(!uid||uid===O.user?.id))proof=stamp();if(current()){this.verified=null;this.phase=navigator.onLine===false?'offline':'error';this.error=O.errorText(error);}}
  finally{if(this.connecting===job)this.connecting=null;if(this.job===job)this.job=null;if(current())this.repaint();}})();return job.promise;
 },
 card(p){const selected=p.id===V7.routeState?.subscriptionPlan;return`<button type="button" class="v85-plan ${selected?'is-selected':''}" data-v85-subscription="select" data-id="${esc(p.id)}" aria-pressed="${selected}"><span class="v85-plan-top"><strong><span class="v85-plan-emblem" aria-hidden="true">${Number(p.duration_days)===30?'✨':Number(p.duration_days)===180?'💎':Number(p.duration_days)===365?'👑':'✦'}</span>${esc(loc(p.labels)||p.id)}</strong><span class="v85-plan-choice" aria-hidden="true">${selected?'✓':'+'}</span></span><span class="v85-plan-duration">${esc(duration(p))}</span><strong class="v85-plan-price"><bdi>${esc(ascii(price(p.price_minor,p.currency)))}</bdi></strong><span class="v85-plan-total">${esc(t('total'))}</span><span class="v85-plan-pick">${esc(t(selected?'selected':'select'))}<span aria-hidden="true">←</span></span></button>`;},
 statusHTML(){const state=this.licenseState(),sub=state.sub,plan=sub&&this.plans().find(p=>p.id===sub.plan_id),summary=t(state.kind==='local'?'localPlan':state.kind),end=sub?.ends_at==='infinity'?t('unlimited'):sub?.ends_at&&Number.isFinite(Date.parse(sub.ends_at))?new Date(sub.ends_at).toLocaleDateString(A.prefs.language,{numberingSystem:'latn'}):'',network=navigator.onLine===false?'browserOffline':'browserOnline';return`<section class="v87-plan-status panel" data-entitlement="${esc(state.kind)}"><div><small>${esc(t('current'))}</small><strong>${esc(summary)}</strong>${plan?`<span>${esc(loc(plan.labels)||plan.id)}</span>`:''}${end?`<small>${esc(t('expires'))} <bdi>${esc(ascii(end))}</bdi></small>`:''}${state.cached?`<small>${esc(t('cachedStatus'))}</small>`:''}</div><div><small>${esc(t('connection'))}</small><strong>${root.MasarifiConnection?.icon(navigator.onLine===false?'offline':'online')||''}${esc(t(network))}</strong></div></section>${state.pending.map(r=>this.pendingHTML(r)).join('')}`;},
 pendingHTML(r,checkout=false){return`<section class="v85-pending ${checkout?'v85-checkout panel':''}" data-pending-request="${esc(r.id)}"><div><strong>${esc(t('pending'))}</strong><bdi>${esc(ascii(r.request_no||''))}</bdi><p>${esc(t('existingRequest'))}</p>${quote(r)?`<small class="v85-stored-quote">${esc(t('requestQuote'))}: <bdi>${esc(ascii(quote(r)))}</bdi></small>`:''}</div>${action('request',t('openRequest'),`data-id="${esc(r.id)}"`,'primary')}</section>`;},
 checkoutHTML(p){const pending=this.pendingRequests()[0];if(pending)return this.pendingHTML(pending,true);if(!p)return`<section class="v85-checkout v85-checkout-empty panel"><span aria-hidden="true">${root.ico?.('wallet')||'◎'}</span><h2>${esc(t('pick'))}</h2><p>${esc(t('review'))}</p></section>`;const instructions=loc(O.settings?.payment_instructions),allowed=this.verifiedNow()&&!this.ambiguous&&!this.sending&&!this.request;return`<form id="v85SubscriptionRequest" class="v85-checkout panel" data-plan="${esc(p.id)}" aria-busy="${this.sending}" ${this.sending?'data-busy="1"':''}><div class="v85-checkout-heading"><span class="v85-overline">${esc(t('selected'))}</span><h2>${esc(t('checkout'))}</h2></div><div class="v85-order"><div><strong>${esc(loc(p.labels)||p.id)}</strong><small>${esc(duration(p))}</small></div><div class="v85-order-price"><bdi>${esc(ascii(this.request&&quote(this.request)||price(p.price_minor,p.currency)))}</bdi>${this.request&&quote(this.request)?`<small>${esc(t('requestQuote'))}</small>`:''}</div></div><div class="v85-payment"><h3>${esc(t('payment'))}</h3><p>${esc(instructions||t('instructionsMissing'))}</p></div><label class="v85-reference">${esc(t('reference'))} <small>· ${esc(t('optional'))}</small><input name="reference" maxlength="300" autocomplete="off" value="" ${this.request||this.sending?'readonly':''}></label><p class="hint">${esc(t('referenceHint'))}</p><p class="v85-review">${esc(t('review'))}</p><p class="form-error" role="alert">${esc(this.error||'')}</p>${this.note?`<p class="v85-request-note" role="status">${esc(this.note)}</p>`:''}<div class="v85-checkout-actions">${this.request?action('request',t('openRequest'),`data-id="${esc(this.request.id)}"`,'primary'):`<button type="submit" class="primary" ${allowed?'':'disabled'}>${esc(t(this.sending?'sending':'submit'))}</button>`}${action('contact',t('contact'),'','v85-contact-link')}</div></form>`;},
 page(){this.syncScope();if(this.request&&this.request.plan!==V7.routeState?.subscriptionPlan){this.request=null;this.note='';}const plans=this.plans(),main=plans.filter(p=>[30,180,365].includes(Number(p.duration_days))),other=plans.filter(p=>!main.includes(p)),p=this.selected(),state=this.phase==='loading'?'preparing':navigator.onLine===false?'offline':O.networkPaused||!this.connected()?'local':this.phase==='error'?'error':this.verifiedNow()?'':'stale';main.sort((a,b)=>Number(a.duration_days)-Number(b.duration_days));return`<div class="v85-subscription-page">${this.statusHTML()}<section class="v85-subscription-hero"><span class="v85-hero-mark" aria-hidden="true">✨</span><span class="v85-overline">MASARIFI ONLINE</span><h2>${esc(t('eyebrow'))}</h2><p>${esc(t('intro'))}</p><div class="v85-subscription-hero-actions">${action('messages',t('messages'))}${action('contact',t('contact'))}${action('refresh',t(this.connected()?'refresh':'connect'))}</div></section>${!p&&(this.note||this.error)?`<p class="v85-request-note" role="status">${esc(this.note||this.error)}</p>`:''}${state?`<section class="v85-subscription-connection" role="status"><div>${this.phase==='loading'?'<span class="spinner" aria-hidden="true"></span>':''}<p>${esc(t(state))}</p></div>${this.phase==='loading'?'':action('refresh',t(this.connected()?'refresh':'connect'),'','v85-refresh')}</section>`:''}<div class="v85-subscription-layout"><section class="v85-subscription-plans" aria-labelledby="v85PlansTitle"><div class="v85-section-heading"><span class="v85-overline">${esc(t('total'))}</span><h2 id="v85PlansTitle">${esc(t('choose'))}</h2></div><p class="v85-plan-scroll-hint" id="v85PlanScrollHint">${esc(t('browseHint'))}</p><div class="v85-plan-row" tabindex="0" role="region" aria-labelledby="v85PlansTitle" aria-describedby="v85PlanScrollHint"><div class="v85-plan-grid">${(main.length?main:plans).map(x=>this.card(x)).join('')||`<div class="panel v85-plans-empty"><p>${esc(t('empty'))}</p>${action('contact',t('contact'))}</div>`}</div></div>${main.length&&other.length?`<details class="v85-more-plans" ${other.some(x=>x.id===p?.id)?'open':''}><summary>${esc(t('other'))}</summary><div class="v85-plan-grid v85-plan-grid-extra">${other.map(x=>this.card(x)).join('')}</div></details>`:''}<section class="v85-subscription-steps"><h3>${esc(t('steps'))}</h3><ol>${['step1','step2','step3'].map(key=>`<li>${esc(t(key))}</li>`).join('')}</ol><p>${esc(t('free'))}</p></section></section>${this.checkoutHTML(p)}</div></div>`;},
 mount(){if(A.locked||A.page!=='subscription'||guest())return;this.syncScope();if(this.request&&this.request.plan!==V7.routeState?.subscriptionPlan)this.request=null;const form=doc.getElementById('v85SubscriptionRequest');if(form){root.MasarifiInteraction?.track?.(form);if(this.referencePlan===form.dataset.plan)form.elements.reference.value=this.reference;else{this.reference='';this.referencePlan=form.dataset.plan;}if(this.request)root.MasarifiInteraction?.markSaved?.(form);else if(form.elements.reference.value)root.MasarifiInteraction?.touch?.(form);form.onsubmit=event=>{event.preventDefault();this.submit(form).catch(error=>A.error?.(error));};}if(this.phase==='idle'){if(this.connected())this.load(false);else this.phase=navigator.onLine===false?'offline':'local';}},
 repaint(){if(A.locked||A.page!=='subscription')return;this.capture();A.render();},
 async leaveGuard(){const host=doc.getElementById('content'),interaction=root.MasarifiInteraction;return interaction?.requestLeave?await interaction.requestLeave(host):interaction?.canLeave?.(host)!==false;},
 async service(kind,id){const proof=stamp();if(A.locked||guest()||!await this.leaveGuard())return;if(A.locked||A.page!=='subscription'||!same(proof,stamp()))return;const form=doc.getElementById('v85SubscriptionRequest');if(form)root.MasarifiInteraction?.markSaved?.(form);this.reference='';this.referencePlan='';if(kind==='messages')return S.loadHome();return S.open(kind==='request'?id:null);},
 async submit(form){
  if(A.locked||guest()||A.page!=='subscription'||doc.getElementById('v85SubscriptionRequest')!==form||this.sending||this.ambiguous||this.request||this.pendingRequests().length)return;
  this.capture();const p=this.selected();if(!p||p.id!==form.dataset.plan||!this.verifiedNow())return;const proof=stamp(),seq=this.seq,quote=signature(p),reference=this.reference;const scopeCurrent=()=>this.current(proof,seq)&&V7.routeState?.subscriptionPlan===p.id,current=()=>scopeCurrent()&&doc.getElementById('v85SubscriptionRequest')===form;
  this.sending=true;form.elements.reference.readOnly=true;form.setAttribute('aria-busy','true');form.dataset.busy='1';const button=form.querySelector('[type=submit]'),error=form.querySelector('.form-error');button.disabled=true;button.textContent=t('sending');error.textContent='';this.error='';this.note='';let creating=false;
  try{const session=await O.requestSession();if(!current())return;await O.fetchPublic();if(!current())return;await O.checkSession(session);if(!current())return;const requests=await O.select('subscription_requests');if(!current())return;O.requests=requests;const pending=this.pendingForUser(requests,proof.uid)[0];if(pending){this.note=t('existingRequest');return;}if(!this.verifiedNow())return;const live=this.plans().find(x=>x.id===p.id);if(!live||signature(live)!==quote){this.note=t(live?'changed':'removed');this.verified=proof;return;}
   creating=true;const request=await O.createRequest({plan:live.id,email:'',phone:'',reference,receipt:null});if(!scopeCurrent())return;await O.checkSession(session);if(!scopeCurrent())return;this.request=request;this.note=t((O.requests||[]).some(r=>r.id===request.id)?'existingRequest':'requestSaved');this.ambiguous=false;const activeForm=doc.getElementById('v85SubscriptionRequest');root.MasarifiInteraction?.markSaved?.(activeForm||form);
   this.sending=false;for(const target of [form,activeForm].filter(Boolean)){target.setAttribute('aria-busy','false');delete target.dataset.busy;}
   try{await S.open(request.id);}catch(error){if(this.current(proof,seq))this.error=O.errorText(error);}
  }catch(error){if(scopeCurrent()){this.error=O.errorText(error);if(creating&&['network_timeout','Failed to fetch','NetworkError'].some(code=>String(error?.message||'').includes(code))){this.ambiguous=true;this.note=t('ambiguous');}}}
  finally{if(scopeCurrent()){this.sending=false;const activeForm=doc.getElementById('v85SubscriptionRequest');for(const target of [form,activeForm].filter(Boolean)){target.setAttribute('aria-busy','false');delete target.dataset.busy;}this.repaint();}}
 }
};
V6.routes.add('subscription');V7.pages.subscription=()=>P.page();
const title=V7.title;V7.title=function(){return A.page==='subscription'?t('title'):title.apply(this,arguments);};
const key=V7.routeKey;V7.routeKey=function(state){return key.call(this,state)+'|'+String(state?.subscriptionPlan||'');};
const capture=V7.captureRouteState;V7.captureRouteState=function(){if(A.page==='subscription')P.capture();return capture.apply(this,arguments);};
const mount=V7.mount;V7.mount=function(){const result=mount.apply(this,arguments);P.mount();return result;};
const render=A.render;A.render=function(){if(A.page==='subscription')P.capture();const result=render.apply(this,arguments);doc.body.classList.toggle('v85-subscription-route',!A.locked&&A.page==='subscription');return result;};
const invalidate=O.invalidateSession;O.invalidateSession=function(){if(P.connecting){P.verified=null;P.scope=null;P.reference='';P.referencePlan='';P.request=null;P.ambiguous=false;}else P.invalidate();const result=invalidate.apply(this,arguments);if(!A.locked&&A.page==='subscription')P.repaint();return result;};
O.subscriptionForm=()=>P.open();S.choosePlan=id=>P.choose(id);
doc.addEventListener('click',event=>{const button=event.target.closest?.('[data-v85-subscription]');if(!button||A.locked)return;event.preventDefault();event.stopImmediatePropagation();const kind=button.dataset.v85Subscription,id=button.dataset.id;const promise=kind==='select'?P.choose(id):kind==='refresh'?P.load(!P.connected()):P.service(kind,id);Promise.resolve(promise).catch(error=>{if(!A.locked&&A.page==='subscription'){P.error=O.errorText(error);P.repaint();}});},true);
doc.addEventListener('masarifi:navigation',()=>{if(A.page!=='subscription'){P.seq++;P.job=null;P.connecting=null;P.verified=null;P.phase='idle';P.reference='';P.referencePlan='';P.sending=false;P.error='';P.note='';}});
Promise.resolve(O.ready).then(()=>{if(A.page==='subscription'&&!A.locked&&!guest()&&!P.sending&&!P.job){if(P.connected())P.load(false);else P.repaint();}}).catch(()=>{});
root.addEventListener('v6:locked',()=>P.invalidate());
root.addEventListener('offline',()=>{P.verified=null;P.phase='offline';if(!P.sending)P.repaint();});
root.addEventListener('online',()=>{if(A.page==='subscription'&&!A.locked&&!O.networkPaused&&!P.sending)P.load(false);});
})(window);

