/* Own user profile: personal storage stays local; authenticated publication is optional. */
(function(root){'use strict';
const app=root.App,O=root.Online,W=O?.Workspace,F=O?.FamilyUI;if(!app||!O||!W||!F||root.MasarifiUserProfile)return;
const P=root.MasarifiUserProfile={flights:new Map(),loaded:new Set(),localSignature:'',sequence:0,editRevision:0,status:'local',lastError:''};
V7.addLabels(`
profilePending|حُفظ محليًا؛ بانتظار إرسال الاسم والصورة.|Yerelde kaydedildi; ad ve fotoğraf gönderilmeyi bekliyor.|Saved locally; name and photo are waiting to send.|Enregistré localement ; nom et photo en attente d’envoi.|Herêmî tomar bû; nav û wêne li benda şandinê ne.
profileSynced|تم إرسال الاسم والصورة إلى الإدارة.|Ad ve fotoğraf yönetime gönderildi.|Name and photo sent to administration.|Nom et photo envoyés à l’administration.|Nav û wêne ji rêveberiyê re hatin şandin.
profileLocal|الاسم والصورة محفوظان على هذا الجهاز.|Ad ve fotoğraf bu cihazda kayıtlı.|Name and photo are saved on this device.|Nom et photo enregistrés sur cet appareil.|Nav û wêne li ser vê cîhazê parastî ne.
profileRetry|إعادة إرسال الملف الشخصي|Profili yeniden gönder|Retry profile delivery|Réessayer l’envoi du profil|Şandina profilê dîsa biceribîne
`);
const stamp=()=>({uid:O.user?.id||null,auth:O.authEpoch,mode:O.modeEpoch,lock:V5.lockGeneration||0,installation:O.installation?.id||null});
const current=s=>!!s&&!app.locked&&s.uid===(O.user?.id||null)&&s.auth===O.authEpoch&&s.mode===O.modeEpoch&&s.lock===(V5.lockGeneration||0)&&s.installation===(O.installation?.id||null);
const scope=s=>[s.uid,s.auth,s.mode,s.installation].join('|'),key=uid=>'ownProfile:'+uid;
const local=p=>JSON.stringify([String(p?.username||''),String(p?.avatar||'')]);
const ready=s=>current(s)&&!!s.uid&&!O.user?.localOnly&&!O.networkPaused&&O.sessionReady&&navigator.onLine!==false&&document.visibilityState!=='hidden';
const empty=uid=>({uid,pending:null,publishedSignature:null,server:null,migrated:false});
P.read=async uid=>(await DB.get('meta',key(uid)))?.value||empty(uid);
// Compare and mutate the latest record in one serialized IndexedDB transaction across tabs.
P.update=(s,change)=>new Promise((resolve,reject)=>{if(!DB.db||!s.uid||!current(s)){resolve(null);return;}const tx=DB.db.transaction('meta','readwrite'),store=tx.objectStore('meta');let value;tx.oncomplete=()=>resolve(value);tx.onabort=tx.onerror=()=>reject(tx.error||Error('storageError'));const req=store.get(key(s.uid));req.onsuccess=()=>{if(!current(s))return;const previous=req.result?.value||empty(s.uid);if(previous.uid!==s.uid)return;value=change(previous);if(value)store.put({id:key(s.uid),value});};});
P.validAvatar=data=>{if(!data)return true;if(typeof data!=='string'||data.length>87410||!/^data:image\/(jpeg|webp);base64,[A-Za-z0-9+/]+={0,2}$/.test(data))return false;const encoded=data.split(',')[1];if(encoded.length%4)return false;try{const b=atob(encoded),n=b.length,byte=i=>b.charCodeAt(i);if(n<12||n>65536)return false;if(data.startsWith('data:image/jpeg;'))return byte(0)===255&&byte(1)===216&&byte(2)===255&&byte(n-2)===255&&byte(n-1)===217;return b.slice(0,4)==='RIFF'&&b.slice(8,12)==='WEBP'&&['VP8 ','VP8L','VP8X'].includes(b.slice(12,16))&&byte(4)+byte(5)*256+byte(6)*65536+byte(7)*16777216===n-8;}catch{return false;}};
P.prepare=async profile=>{const name=String(profile?.display_name||'').trim();if(!name||Array.from(name).length>120||new TextEncoder().encode(name).length>480||/[\x00-\x1f\x7f-\x9f]/.test(name))throw Error('required');let avatar=profile?.avatar_data_url||null;if(avatar&&!P.validAvatar(avatar)){if(typeof avatar!=='string'||!/^data:image\/(jpeg|png|webp);base64,[A-Za-z0-9+/]+={0,2}$/.test(avatar)||avatar.length>400000)throw Error('photoInvalid');let raw;try{raw=atob(avatar.split(',')[1]);}catch{throw Error('photoInvalid');}avatar=await F.thumbnail(new Blob([Uint8Array.from(raw,c=>c.charCodeAt(0))],{type:avatar.slice(5,avatar.indexOf(';'))}));if(!avatar||!P.validAvatar(avatar))throw Error('photoInvalid');}return{display_name:name,avatar_data_url:avatar};};
P.signature=async p=>Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(JSON.stringify([p.display_name,p.avatar_data_url||null])))),b=>b.toString(16).padStart(2,'0')).join('');
P.paint=function(){if(app.locked)return;for(const node of document.querySelectorAll('[data-profile-status]')){node.textContent=tr(P.status==='synced'?'profileSynced':P.status==='pending'?'profilePending':'profileLocal');const next=node.parentElement?.querySelector('[data-profile-retry]');if(next)next.hidden=P.status!=='pending';}};
P.mark=(status,error='')=>{P.status=status;P.lastError=error;P.paint();};
P.schedule=function(ms=600){clearTimeout(P.timer);P.timer=setTimeout(()=>{P.timer=null;P.flush().catch(()=>{});},ms);};
P.queue=async function(profile,s=stamp()){if(!s.uid||!current(s))return null;const seq=++P.sequence,wanted=await P.prepare(profile),signature=await P.signature(wanted);if(!current(s)||seq!==P.sequence)return null;const record=await P.update(s,old=>{if(old.pending?.signature===signature||!old.pending&&old.publishedSignature===signature)return old;return{...old,migrated:true,pending:{id:crypto.randomUUID(),signature,profile:wanted,createdAt:Date.now()}};});if(current(s)){P.mark(record?.pending?'pending':record?.publishedSignature?'synced':'local');if(record?.pending)P.schedule();}return record;};
P.flush=function(){const s=stamp();if(!ready(s))return Promise.resolve(false);const id=scope(s);if(P.flights.has(id))return P.flights.get(id);const flight=(async()=>{let row;try{row=await P.read(s.uid);if(!ready(s)||!row.pending||row.uid!==s.uid)return false;const pending=row.pending,proof=await O.requestSession();if(!ready(s))return false;const result=await O.rpc('user_profile',{p_installation_id:s.installation,p_display_name:pending.profile.display_name,p_avatar_data_url:pending.profile.avatar_data_url||null});await O.checkSession(proof);if(!ready(s)||result?.ok!==true||result.data?.user_id!==s.uid)return false;const updated=await P.update(s,latest=>latest.pending?.id===pending.id&&latest.pending?.signature===pending.signature?{...latest,pending:null,publishedSignature:pending.signature,server:result.data}:latest);if(!current(s))return false;P.mark(updated?.pending?'pending':'synced');if(W.identity===s.uid&&W.summary){W.summary.display_name=result.data.display_name;W.summary.avatar_data_url=result.data.avatar_data_url;}if(updated?.pending)P.schedule(600);return true;}catch(error){if(current(s)&&row?.pending){P.mark('pending',error.message);if(ready(s))P.schedule(15000);}return false;}})().finally(()=>{if(P.flights.get(id)===flight)P.flights.delete(id);});P.flights.set(id,flight);return flight;};
const isGuest=()=>W.guest()||!!O.guestSubs?.length||W.summary?.boxes?.some(b=>b.role!=='owner')&&!W.summary?.boxes?.some(b=>b.role==='owner');
P.bootstrap=async function(){const s=stamp(),id=scope(s);if(!ready(s)||P.loaded.has(id)||!W.summary)return false;P.loaded.add(id);let complete=false;try{const proof=await O.requestSession(),result=await O.rpc('user_profile',{p_installation_id:s.installation,p_display_name:null,p_avatar_data_url:null});await O.checkSession(proof);if(!ready(s)||result?.ok!==true||result.data?.user_id!==s.uid)return false;const guest=isGuest(),record=await P.update(s,old=>({...old,server:result.data,migrated:old.migrated||guest}));if(!record||!current(s))return false;if(record.pending){P.mark('pending');P.schedule();}else if(!record.migrated&&!guest&&String(app.prefs.username||'').trim()){const queued=await P.queue({display_name:app.prefs.username,avatar_data_url:app.prefs.avatar||null},s);if(!queued||!current(s))return false;}else P.mark(record.publishedSignature?'synced':'local');complete=true;return true;}catch{return false;}finally{if(!complete)P.loaded.delete(id);}};
const collect=async(prefs,s)=>{const signature=local(prefs);if(signature===P.localSignature)return;if(!current(s))return;if(!s.uid||!String(prefs.username||'').trim()){P.localSignature=signature;P.mark('local');return;}try{const record=await P.queue({display_name:prefs.username,avatar_data_url:prefs.avatar||null},s);if(record&&current(s))P.localSignature=signature;}catch(e){if(current(s))P.mark('pending',e.message);}};
const load=app.load;app.load=async function(){const result=await load.apply(this,arguments);P.localSignature=local(this.prefs);return result;};
const savePrefs=app.savePrefs;app.savePrefs=async function(next){P.editRevision++;const s=stamp(),wanted=structuredClone(next),result=await savePrefs.apply(this,arguments);if(current(s))await collect(wanted,s);return result;};
const prefsSave=app.prefsSave;app.prefsSave=async function(){P.editRevision++;const s=stamp(),wanted=structuredClone(this.prefs),result=await prefsSave.apply(this,arguments);if(current(s))await collect(wanted,s);return result;};
P.localSignature=local(app.prefs);
// Preserve the existing 512px local portrait; defer any private thumbnail conversion to the queue.
V5.pickPhoto=function(){if(app.locked)return;const s=stamp(),revision=++P.editRevision,starting=local(app.prefs),input=document.createElement('input');input.type='file';input.accept='image/jpeg,image/png,image/webp,image/avif';input.hidden=true;document.body.append(input);V5.pickingUntil=Date.now()+120000;const valid=()=>current(s)&&revision===P.editRevision&&starting===local(app.prefs);const clean=()=>{V5.pickingUntil=0;input.remove();};input.oncancel=clean;input.onchange=async()=>{let canvas;try{const file=input.files?.[0];if(!file||!valid())return;const photo=await Photos.compress(file);if(!valid())return;const image=await Photos.decode(photo.data);if(!valid())return;const scale=Math.min(1,512/Math.max(image.width,image.height));canvas=document.createElement('canvas');canvas.width=Math.max(1,Math.round(image.width*scale));canvas.height=Math.max(1,Math.round(image.height*scale));canvas.getContext('2d').drawImage(image,0,0,canvas.width,canvas.height);const avatar=canvas.toDataURL('image/jpeg',.84);if(avatar.length>=400000)throw Error('photoLarge');if(!valid())return;const next=structuredClone({...app.prefs,avatar}),operation=++P.editRevision;await DB.put('meta',{id:'prefs',value:next});if(!current(s)||operation!==P.editRevision||starting!==local(app.prefs))return;app.prefs=next;await collect(next,s);if(!current(s)||operation!==P.editRevision)return;app.render();app.toast(tr('saved'));}catch(error){if(current(s))app.error(error);}finally{if(canvas)canvas.width=canvas.height=1;clean();}};input.click();};
// Self profile is separate from owner-assigned per-box member profiles.
W.profile=function(){if(app.locked||!O.user)return;const s=stamp(),initial={display_name:W.summary?.display_name||(!isGuest()?app.prefs.username:'')||'',avatar_data_url:W.summary?.avatar_data_url||null},dialog=O.modal(W.t('profile'),F.profileFields(initial)+`<p data-profile-status role="status" aria-live="polite"></p><button type="button" data-profile-retry>${E(tr('profileRetry'))}</button>`,async(data,form)=>{if(!current(s)||!form?.isConnected||!form.closest('dialog')?.open)return false;if(form.familyPhotoBusy)throw Error('photoBusy');const record=await P.queue({display_name:data.get('display_name'),avatar_data_url:form.familyAvatar||null},s);if(!current(s)||!record)return false;App.toast(tr('profilePending'));return true;});const form=dialog.querySelector('form');form.dataset.familyForm='own-profile';F.mountProfile(form,initial);P.paint();P.read(s.uid).then(row=>{if(!current(s)||!form.isConnected||!form.closest('dialog')?.open)return;const profile=row.pending?.profile||row.server;if(profile&&form.elements?.display_name?.value===initial.display_name&&form.familyAvatar===(initial.avatar_data_url||'')&&!form.familyPhotoBusy){form.elements.display_name.value=profile.display_name;form.familyAvatar=profile.avatar_data_url||'';form.elements.display_name.dispatchEvent(new Event('input',{bubbles:true}));}}).catch(()=>{});return dialog;};
const settings=app.settingsPage;app.settingsPage=function(){const html=settings.apply(this,arguments);if(V6.settingsSection!=='profile')return html;return html+`<section class="panel"><p data-profile-status role="status" aria-live="polite">${E(tr(P.status==='pending'?'profilePending':P.status==='synced'?'profileSynced':'profileLocal'))}</p><button type="button" data-profile-retry${P.status==='pending'?'':' hidden'}>${E(tr('profileRetry'))}</button></section>`;};
const refresh=W.refresh;W.refresh=async function(){const r=await refresh.apply(this,arguments);P.bootstrap().catch(()=>{});P.schedule();return r;};
const rpc=O.rpc;O.rpc=async function(name){const s=stamp(),r=await rpc.apply(this,arguments);if(name!=='user_profile'&&current(s)&&r?.ok!==false)P.schedule();return r;};
const enable=O.enableOnline;O.enableOnline=async function(){const r=await enable.apply(this,arguments);P.bootstrap().catch(()=>{});P.schedule();return r;};
root.addEventListener('online',()=>{if(!O.networkPaused){P.bootstrap().catch(()=>{});P.schedule(300);}});
document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='visible'){P.bootstrap().catch(()=>{});P.schedule(300);}});
document.addEventListener('click',event=>{const b=event.target.closest('[data-profile-retry]');if(!b||app.locked)return;event.preventDefault();P.flush().catch(()=>{});});
})(window);
