/* Route-aware chrome; existing controllers retain ownership of saves and navigation. */
(function(root){'use strict';const A=root.App,V=root.V6,doc=root.document;if(!A||!V)return;
V.addLabels(`v87Restore|استعادة الافتراضي|Varsayılanları geri yükle|Restore defaults|Rétablir les valeurs par défaut`);
function decorate(){if(A.locked)return;const settings=A.page==='settings';doc.body.dataset.settings=settings?'true':'false';const content=doc.getElementById('content'),heading=content?.querySelector(':scope > .page-heading'),title=heading?.querySelector('h1')?.textContent||root.V7?.title?.()||root.tr(A.page),brand=doc.querySelector('#header .brand strong');if(brand){brand.textContent=title;brand.title=title;brand.setAttribute('aria-label',title);}doc.title=title+' · '+root.tr('app');heading?.classList.add('route-heading-redundant');const sub=doc.querySelector('#header .brand small');if(sub)sub.textContent=settings?root.tr('settings'):root.SectionPreferences?.label?.(A.prefs.section)||root.tr(A.prefs.section);
const form=doc.getElementById('v6Prefs');if(settings&&V.settingsSection==='appearance'&&form&&!form.querySelector('[data-v87-reset]')){const b=doc.createElement('button');b.type='button';b.dataset.v87Reset='appearance';b.textContent=root.tr('v87Restore');form.querySelector('.settings-save')?.prepend(b);}
const footer=settings?content?.querySelector('.settings-save'):null;doc.body.dataset.settingsActions=footer?'true':'false';if(footer){footer.setAttribute('aria-label',root.tr('save'));const h=footer.getBoundingClientRect().height;doc.documentElement.style.setProperty('--context-footer-height',Math.ceil(h)+'px');}const overview=content?.querySelector('.home-overview'),greeting=content?.querySelector('.home-heading');if(overview&&greeting)greeting.after(overview);
if(settings&&V.settingsSection==='home-layout')content?.querySelector('#v7HomePrefs > div > h2')?.classList.add('route-heading-redundant');}
doc.addEventListener('click',e=>{const b=e.target.closest?.('[data-v87-reset]');if(!b||A.locked)return;const form=b.closest('form');if(!form)return;for(const [name,value]of Object.entries({languageMode:'system',theme:'system',fontSize:'16'})){const input=form.elements[name];if(input){input.value=value;input.dispatchEvent(new Event('input',{bubbles:true}));input.dispatchEvent(new Event('change',{bubbles:true}));}}if(form.elements.compact)form.elements.compact.checked=false;root.MasarifiInteraction?.touch?.(form);});
const render=A.render;A.render=function(){const result=render.apply(this,arguments);decorate();return result;};root.addEventListener('resize',decorate);doc.addEventListener('masarifi:navigation',decorate);root.MasarifiWorkspacePolish={decorate};
})(window);
